### ISSUE TITLE
Winetricks doesn't start with Wine installed system-wide

### ISSUE THREAD

**Issue by tannisroot** [lutris/lutris#1085]
Lutris from master has non-working winetricks, it just doesn't start, even when it's used in scripts.
Replacing it with upstream winetricks doesn't fix it.
lutris -d output: https://paste.ubuntu.com/p/Kqvv4MSBr2/

**Comment by tannisroot** [comment]
Works with runtime disabled

**Comment by jcstryker** [comment]
Still not working with 0.4.19 with a fresh runtime folder
https://privatebin.net/?107944177bf0be2c#xxQos/dOXkj9FhPhJyV4Siu5nEVnG/u1bhsWjiINjKA=

**Comment by Medath** [comment]
Happening to me too with the same log output as the other two reports

**Comment by Medath** [comment]
It happens on my native Solus install and some of my VMs (Manjaro and Elementary OS). All show pretty much the same output and disabling the Lutris runtime makes winetricks work again. Using the bisection method as described [here](https://github.com/lutris/lutris/wiki/Lutris-Runtime#debugging-runtime-issues) seems to have no effects.

It also happens on a Fedora 28 VM, but the [output](https://gist.github.com/Medath/b2af81191b00fd13b2ef68954a6ef53c) is quite different from the other cases. Disabling the Lutris runtime or renaming lib64 and steam inside the lutris runtime folder seems to make winetricks work again. I did not go much deeper in there because I have no idea what I'm doing and because this only happens on fedora and not all the other systems.

On Ubuntu winetricks works as expected even with the Lutris runtime enabled.

**Comment by strycore** [comment]
I pushed a runtime update based on @Medath 's console output, with libhogweed and libthai removed. Please test again.

**Comment by tannisroot** [comment]
Uninstalling just Wine package from the system, but leaving all of it dependencies seems to solve this. Can anyone else confirm?

**Comment by Medath** [comment]
The runtime update changed nothing for Solus and Manjaro. On Fedora it also still doesn't launch, but it complains about different things now. I highly doubt the Fedora issue is related to this issue. I could still continue testing here and open a separate issue on the buildbot with the individual offending files.

Removing system wine on Solus and Manjaro actually worked.

**Comment by tannisroot** [comment]
Totally shooting in the sky here, but it may have something to do with how Lutris detects wine and disables the runtime if it finds it.

**Comment by soredake** [comment]
For me winetricks doesn't and freezing lutris when dxvk set to `Manual`:
```
❯ lutris -d
WARNING  2018-09-07 09:31:43,612 [application]:This version of Gtk doesn't support set_option_context_summary
DEBUG    2018-09-07 09:31:43,896 [runtime]:Runtime disabled, not updating it.
INFO     2018-09-07 09:31:43,896 [lutriswindow]:Connected to lutris.net as soredake
DEBUG    2018-09-07 09:31:43,917 [api]:Fetching game library
ERROR    2018-09-07 09:31:44,119 [steam]:Steam config /home/bausch/.local/share/lutris/runners/winesteam/prefix/drive_c/Program Files/Steam/config/config.vdf is empty: 'Steam'
DEBUG    2018-09-07 09:31:44,120 [steam]:Watching Steam folder /home/bausch/.local/share/Steam/steamapps
DEBUG    2018-09-07 09:31:44,121 [steam]:Watching Steam folder /media/disk0/SteamLibraryLinux/steamapps
DEBUG    2018-09-07 09:31:44,121 [steam]:Watching Steam folder /home/bausch/.local/share/lutris/runners/winesteam/prefix/drive_c/Program Files/Steam/steamapps
DEBUG    2018-09-07 09:31:50,832 [downloader]:Starting download of:
 https://github.com/doitsujin/dxvk/releases/download/vManual/dxvk-Manual.tar.gz
ERROR    2018-09-07 09:31:51,430 [http]:Unavailable url (https://github.com/doitsujin/dxvk/releases/download/vManual/dxvk-Manual.tar.gz): HTTP Error 404: Not Found
```

**Comment by tannisroot** [comment]
@soredake please open a separate issue, doesn't seem to match what other get in debug mode.

**Comment by tannisroot** [comment]
This issue is getting a bit messy, closing this one to reopen a new one.
