### ISSUE TITLE
wont run on opensuse tumbleweed

### ISSUE THREAD

**Issue by darylkuchay** [lutris/lutris#1276]
daryl@G7:~> lutris
```
Traceback (most recent call last):
  File "/usr/bin/lutris", line 33, in <module>
    from lutris.gui.application import Application
  File "/usr/lib/python3.6/site-packages/lutris/gui/application.py", line 27, in <module>
    gi.require_version('Gdk', '3.0')
  File "/usr/lib64/python3.6/site-packages/gi/__init__.py", line 127, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gdk not available

```
It almost looks like a gtk library but I am unsure of what to install to satisfy. I pulled a rpm through one click install on yast from https://software.opensuse.org/download.html?project=home%3Astrycore&package=lutris   Please let me know if this is an incorrect place to post.

**Comment by strycore** [comment]
Please install Lutris by adding the repository and not by only installing the RPM.

**Comment by tannisroot** [comment]
Could this be caused by Lutris builds using ancient version of fonttype from Ubuntu 16.04?

**Comment by strycore** [comment]
no.

**Comment by strycore** [comment]
it's cause by installing the package improperly

**Comment by Traace** [comment]
This issue shoudn't be closed, I did a fresh install of openSUSE tubleweed, added strycore repo, installed lutris and get same error as above. 

You want me to open another bug report ? Its pretty ignorant just saying "your fault" and close the issue.

**Comment by darylkuchay** [comment]
Thank you for posting....beat me to the punch. I first tried the official
method by adding the repo to yast. Dont remember the errors. Tried the one
click installer through a web site, also didnt work. Found the rpm and
tried installing that directly. When that didnt work I thought to post.
Apologies if I didnt include the earlier tried steps but please dont close
my post if I didn't violate any forum rules. Folks who are new to linux
coming here for help could easily get turned off by such treatment.

**Comment by strycore** [comment]
Apparently, there's a missing lib in lutris.spec for openSUSE, I'll add it and see if it resolves the issue.

**Comment by darylkuchay** [comment]
Please share results. Seemed GDK referenced GTK and I couldn't figure out which module it was.

**Comment by strycore** [comment]
I added `typelib-1_0-Gtk-3_0` to the lutris.spec file for opensuse, this should fix the issue in the next release.

**Comment by darylkuchay** [comment]
Thank you for the update! I installed

typelib-1_0-Gtk-3_0

via zypper which brought in 3 packages total. Went to one click installer
and agreed to two repos. Installed Lutris and ran from terminal to get:

daryl@G7:~> lutris
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lutris/gui/application.py", line
190, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib/python3.6/site-packages/lutris/gui/lutriswindow.py", line
103, in __init__
    self.show_installed_first
  File "/usr/lib/python3.6/site-packages/lutris/gui/gameviews.py", line 65,
in __init__
    self.store = Gtk.ListStore(int, str, str, Pixbuf, str, str, str, str,
int, str, bool, int, str, str, str)
TypeError: GObject.__init__() takes exactly 0 arguments (15 given)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lutris/gui/application.py", line
323, in do_command_line
    self.window.present()
AttributeError: 'NoneType' object has no attribute 'present'
INFO     2018-11-07 07:40:31,198 [application]:Shutting down Lutris
daryl@G7:~>


Am I missing gobject?

**Comment by Traace** [comment]
Seems like you are still missing some dependencies
TypeError: GObject.__init__() takes exactly 0 arguments (15 given) Traceback (most recent call last):

Maybe python3-gobject-Gdk is needed too? Maybe even some others, try around :+1:

**Comment by darylkuchay** [comment]
That did it. Installed your suggested package and lutris started right up.
Thank you for your assistance! Please close issue as it is solved.

**Comment by Traace** [comment]
Was it only Gdk variant or did you installed both ? :+1:

**Comment by darylkuchay** [comment]
Only sent in a sudo zypper in python3-gobject-Gdk and as it balanced deeps
it brought in what I thought was the same package but ending in Cairo
instead of gdk. I didn't try your second suggestion.

Thank you again!
