### ISSUE TITLE
Tray icon added but not displayed

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/lutris#1603]
It stays there even when Lutris is closed but goes away when I open 0.4.23 cuz I have it disabled there.

I can't even click it.

**Comment by strycore** [comment]
Fixed in f3b636494bee575959a1a1700532f13dee2d4f27

**Comment by AccountOneOff** [comment]
It still gets added when disabled just no icon or context menu.
