### ISSUE TITLE
Emulated games cannot be launched due to symbol lookup error

### ISSUE THREAD

**Issue by Shished** [lutris/lutris#226]
Emulated games does not works when launched in Lutris. All tested emulators (dolphin-emu, mupen64plus, dgen) outputs same error message:
```
symbol lookup error: /usr/lib64/libX11.so.6: undefined symbol: xcb_wait_for_reply64
```
Same error appears even when emulator provided by Lutris being replaced with symlink to system installed emulator.
Used Lutris 0.3.7, installed from official Lutris repo on openSUSE Tumbleweed x86_64.

**Comment by strycore** [comment]
It seems that our runtime is causing problems on Tumbleweed, you can disable it globally in Lutris > Preferences > Show advanced options > Disable Lutris Runtime but I'd rather fix this to that the runtime is compatible with Tumbleweed. Are you running open source graphics drivers or proprietary ones?

**Comment by Shished** [comment]
I'm using proprietary nvidia driver 358.16.

**Comment by strycore** [comment]
OK, so these are the same drivers I'm using on Ubuntu so I suspect that this is cause by some incompatibility in the version of Xorg you're using. If you know a bit about linux libraries, you can try to fix it by modifing the contents in ~/.local/share/lutris/runtime and if you want to start with a fresh runtime, juste delete one or all the folders in the runtime and they will re-download the next time you start lutris.

**Comment by Xodetaetl** [comment]
It looks like an incompatibility between the libx11 library from your system and one of the xcb libs from our runtime. I think I made a mistake by removing libx11 from the Steam runtime.

Alright so, @Shished, can you unpack the following archive directly in your home folder (preserve the archive's folder hierarchy) and see if it fixes your issue?
http://ovocean.com/partage/lutris/runtime/x11-libs.tar.gz

**Comment by Shished** [comment]
After replacing libs from provided archive everything worked.

**Comment by strycore** [comment]
@Xodetaetl were there any particular reason to remove libx11 from the Steam Runtime? Can we put it back?

**Comment by Xodetaetl** [comment]
No good reason, I followed some out-of-context advice from Sullix. We have to put it back.

**Comment by strycore** [comment]
Done, @akien-mga was experiencing the same issue and putting libx11 abck in  the runtime fixed the issue

**Comment by nonchip** [comment]
this is still an issue, with runtime:
```
/home/kyra/.local/share/lutris/runners/retroarch/retroarch: symbol lookup error: /usr/lib/libXv.so.1: undefined symbol: _XEatDataWords
```


without:
```
/home/kyra/.local/share/lutris/runners/retroarch/retroarch: error while loading shared libraries: libCg.so: cannot open shared object file: No such file or directory
```

os: Void Linux with current package versions (probably most importantly `libXv-1.0.11_1`)
