### ISSUE TITLE
UnboundLocalError("local variable 'DESKTOP_FOLDERS' referenced before assignment") when installing game

### ISSUE THREAD

**Issue by Weypare** [lutris/lutris#2501]
**Describe the bug**

During the installation of Magic: The Gathering Arena, after "creating the Wine prefix" step lutris proceeds to show the error message. 

I believe, the bug was introduced in commit https://github.com/lutris/lutris/commit/a31a0a4116d883c3d68fd355f281214de79a9afa. 

**Expected behavior**

Installation successfully finishes.

**Current behavior**

Installation stops at the specified step.

**Lutris debugging output**
```
ERROR    2019-11-30 10:38:36,225 [jobs.target:32]:Error while completing task <bound method CommandsMixin.task of <lutris.installer.interpreter.ScriptInterpreter object at 0x7f5cdee77d30>>: local variable 'DESKTOP_FOLDERS' referenced before assignment
<class 'UnboundLocalError'> local variable 'DESKTOP_FOLDERS' referenced before assignment
  File "/usr/lib/python3.8/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/lutris/installer/commands.py", line 409, in task
    thread = task(**data)
  File "/usr/lib/python3.8/site-packages/lutris/runners/commands/wine.py", line 150, in create_prefix
    prefix_manager.setup_defaults()
  File "/usr/lib/python3.8/site-packages/lutris/util/wine/prefix.py", line 27, in setup_defaults
    self.desktop_integration()
  File "/usr/lib/python3.8/site-packages/lutris/util/wine/prefix.py", line 109, in desktop_integration
    for i, item in enumerate(DESKTOP_FOLDERS):
```

**Screenshots**
![image](https://user-images.githubusercontent.com/17096718/69898309-6164b700-1360-11ea-9240-87c7031e5758.png)

**Comment by ctymoszek** [comment]
I'm getting the same error message when I try to run already-installed applications (World of Warcraft and Twitch client) which previously worked with no issues. This started for me after upgrading from Lutris 0.5.3 to 0.5.4.

**Comment by cr1tterp0wer** [comment]
Same Error Here when launching Overwatch. Worked a few days ago.....

**Comment by ayad-nadeeb** [comment]
Same issue here, Path of Exile.. played and worked just fine last 2 days ago.

**Comment by pfc** [comment]
Same issue, I've just compiled lutris and can no longer play an already installed GuildWars2 installation.
Relevant console info:
```
2019-12-11 22:30:25,836: Couldn't load shell folder name for Desktop
2019-12-11 22:30:25,837: Couldn't load shell folder name for Personal
2019-12-11 22:30:25,837: Couldn't load shell folder name for My Music
2019-12-11 22:30:25,837: Couldn't load shell folder name for My Videos
2019-12-11 22:30:25,837: Couldn't load shell folder name for My Pictures
2019-12-11 22:30:25,837: Error while completing task <bound method wine.prelaunch of <lutris.runners.wine.wine object at 0x7fc81556e7f0>>: local variable 'DESKTOP_FOLDERS' referenced before assignment
<class 'UnboundLocalError'> local variable 'DESKTOP_FOLDERS' referenced before assignment
  File "/usr/lib/python3.8/site-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/lutris/runners/wine.py", line 792, in prelaunch
    self.sandbox(prefix_manager)
  File "/usr/lib/python3.8/site-packages/lutris/runners/wine.py", line 946, in sandbox
    wine_prefix.desktop_integration(
  File "/usr/lib/python3.8/site-packages/lutris/util/wine/prefix.py", line 109, in desktop_integration
    for i, item in enumerate(DESKTOP_FOLDERS):
2019-12-11 22:30:25,838: local variable 'DESKTOP_FOLDERS' referenced before assignment
```

**Comment by pfc** [comment]
A quick fix for anyone interested:
in /usr/lib/python3.8/site-packages/lutris/util/wine/prefix.py add:
`        DESKTOP_FOLDERS = []`
right after 
```
    def desktop_integration(self, desktop_dir=None, restore=False):
        """Overwrite desktop integration"""

```
No clue what this desktop integration override is even supposed to do so I'll leave it to someone familiar with the project to fix in the code base.

**Comment by ctymoszek** [comment]
> A quick fix for anyone interested:
> in /usr/lib/python3.8/site-packages/lutris/util/wine/prefix.py add:
> ` DESKTOP_FOLDERS = []`
> right after
> 
> ```
>     def desktop_integration(self, desktop_dir=None, restore=False):
>         """Overwrite desktop integration"""
>         DESKTOP_FOLDERS = []  #Add here
> ```
> 
> No clue what this desktop integration override is even supposed to do so I'll leave it to someone familiar with the project to fix in the code base.

I assume there's no fix if we don't have Lutris installed from source? I found this thread by Googling the error, but I have Lutris installed from the PPA.

**Comment by pfc** [comment]
> I assume there's no fix if we don't have Lutris installed from source? I found this thread by Googling the error, but I have Lutris installed from the PPA.

Doesn't matter how it is installed, that code is from a python script and can be edited as it compiles at runtime.  One caveat: in trying to get past this error I lost my registry edits for my game.  I'm not sure if that's a coincidence or not.  Not a big deal in my case, just had to reset the dpi.

**Comment by EliaOnceAgain** [comment]
> A quick fix for anyone interested:
> in /usr/lib/python3.8/site-packages/lutris/util/wine/prefix.py add:
> ` DESKTOP_FOLDERS = []`
> right after
> 
> ```
>     def desktop_integration(self, desktop_dir=None, restore=False):
>         """Overwrite desktop integration"""
>         DESKTOP_FOLDERS = []  #Add here
> ```
> 
> No clue what this desktop integration override is even supposed to do so I'll leave it to someone familiar with the project to fix in the code base.

Lutris crashes on launch after this change. Latest version is installed. Did you manage to get it working in any other way?

**Comment by dav-garcia** [comment]
> A quick fix for anyone interested:
> in /usr/lib/python3.8/site-packages/lutris/util/wine/prefix.py add:
> ` DESKTOP_FOLDERS = []`
> right after
> 
> ```
>     def desktop_integration(self, desktop_dir=None, restore=False):
>         """Overwrite desktop integration"""
>         DESKTOP_FOLDERS = []  #Add here
> ```
> 
> No clue what this desktop integration override is even supposed to do so I'll leave it to someone familiar with the project to fix in the code base.

I think a better fix is to declare the global variable within the function, like this:
> ```
>     def desktop_integration(self, desktop_dir=None, restore=False):
>         """Overwrite desktop integration"""
>         global DESKTOP_FOLDERS
> ```

**Comment by pfc** [comment]
This bug has been closed.  I just checked and latest git compiles properly and doesn't require this workaround.  If you're still having this issue then you might need to update your install.

**Comment by Merrit** [comment]
I am running the newest release, 0.5.4 and this still appears to be an issue.

```
merritt@SHODAN:~$ lutris -d
INFO     2020-01-26 16:15:37,355 [application.do_command_line:225]:Running Lutris 0.5.4
INFO     2020-01-26 16:15:37,355 [startup.check_driver:55]:Using NVIDIA drivers 435.21 for x86_64
INFO     2020-01-26 16:15:37,356 [startup.check_driver:60]:GPU: GeForce GTX 960
INFO     2020-01-26 16:15:37,356 [startup.check_driver:79]:GPU: 10DE:1401 1462:3201 using nvidia drivers
INFO     2020-01-26 16:15:37,451 [startup.check_vulkan:132]:Vulkan is supported
INFO     2020-01-26 16:15:37,452 [dxvk.get_dxvk_versions:21]:Updating DXVK versions
DEBUG    2020-01-26 16:15:37,705 [http.get:65]:GET https://lutris.net/api/runtime
DEBUG    2020-01-26 16:15:37,706 [store.get_missing_media:198]:Requesting missing icons from API for yooka-laylee-and-the-impossible-lair
DEBUG    2020-01-26 16:15:37,707 [http.get:65]:GET https://lutris.net/api/games
INFO     2020-01-26 16:15:37,726 [dxvk.get_dxvk_versions:21]:Updating D9VK versions
DEBUG    2020-01-26 16:15:38,166 [api.get_game_api_page:132]:Loaded 1 games from page 1
DEBUG    2020-01-26 16:16:18,237 [application.launch:339]:Launching Yooka-Laylee and the Impossible Lair (wine) (139773619645888)
DEBUG    2020-01-26 16:16:18,274 [game.play:295]:Prelaunching <lutris.runners.wine.wine object at 0x7f1f8fec3e10>
WARNING  2020-01-26 16:16:18,336 [prefix.get_desktop_folders:88]:Couldn't load shell folder name for Desktop
WARNING  2020-01-26 16:16:18,341 [prefix.get_desktop_folders:88]:Couldn't load shell folder name for Personal
WARNING  2020-01-26 16:16:18,346 [prefix.get_desktop_folders:88]:Couldn't load shell folder name for My Music
WARNING  2020-01-26 16:16:18,351 [prefix.get_desktop_folders:88]:Couldn't load shell folder name for My Videos
WARNING  2020-01-26 16:16:18,356 [prefix.get_desktop_folders:88]:Couldn't load shell folder name for My Pictures
ERROR    2020-01-26 16:16:18,357 [jobs.target:32]:Error while completing task <bound method wine.prelaunch of <lutris.runners.wine.wine object at 0x7f1f8fec3e10>>: local variable 'DESKTOP_FOLDERS' referenced before assignment
<class 'UnboundLocalError'> local variable 'DESKTOP_FOLDERS' referenced before assignment
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 30, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 791, in prelaunch
    self.sandbox(prefix_manager)
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 946, in sandbox
    desktop_dir=self.runner_config.get("sandbox_dir")
  File "/usr/lib/python3/dist-packages/lutris/util/wine/prefix.py", line 109, in desktop_integration
    for i, item in enumerate(DESKTOP_FOLDERS):
ERROR    2020-01-26 16:16:18,357 [game.configure_game:312]:local variable 'DESKTOP_FOLDERS' referenced before assignment
ERROR    2020-01-26 16:16:21,565 [game.configure_game:315]:Game prelaunch unsuccessful
TypeError: refresh() takes 1 positional argument but 3 were given
```

**Comment by Gelbpunkt** [comment]
Still an issue when using Lutris 0.5.4, can confirm above. Pops up every time when launching a game, I had to go back to using wine from command line manually.

**Comment by pfc** [comment]
Guys, this bug has been fixed and closed, please stop messaging a dead thread.

IF you have this same bug then you are using old code or an installer compiled from old code. Perhaps the package you are using has not been updated. In that case, you can either use the workaround posted, contact your package maintainer and get them to update or compile the project yourself.

**Comment by Frontrider** [comment]
I see that it's assigned in the "prefix.py" file, but I still get the error.

**Comment by NawTh05** [comment]
Lutris 0.5.4-2 on Manjaro, still getting the error too.

**Comment by pfc** [comment]
Try installing from source.  lutris-git on the AUR works.

**Comment by iharandreyev** [comment]
lowercasing DESKTOP_FOLDERS in prefix.py fixed the issue for me
