### ISSUE TITLE
Lutris not working on Ubuntu 20.04 beta

### ISSUE THREAD

**Issue by apolitech** [lutris/lutris#2669]
**Describe the bug**
Lutris will not start in Ubuntu 20.04 beta

**Expected behavior**
App will run normally after instalation

**Current behavior**

App is not starting

**Steps to reproduce**

- Install Lutris in Ubuntu 20.04 beta
-Run lutris
-

**Lutris debugging output**

Not working

**System information**
Ubuntu Focal Fossa (development branch)
5.4.0-18-generic  
AMD Ryzen 5 1400 Quad-Core Processor
Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (rev c7)

**Screenshots**

[lutris-issue-report.json.zip](https://github.com/lutris/lutris/files/4359332/lutris-issue-report.json.zip)

![Screenshot at 2020-03-20 13-44-42](https://user-images.githubusercontent.com/14872517/77160886-0abaee80-6ab1-11ea-91e5-1395b14ec3c2.png)
![Screenshot at 2020-03-20 13-45-05](https://user-images.githubusercontent.com/14872517/77160893-0b538500-6ab1-11ea-8d02-efe1b6ffbe43.png)

**Comment by JoneKone** [comment]
Can confirm. 

https://hastebin.com/igiwafiyoc.rb

**Comment by DafabHoid** [comment]
I could get it to start by replacing the offending `Gtk.TreeModelSort.sort_new_with_model` with a `Gtk.TreeModelSort.new_with_model` in file gui/views/store.py (which was in /usr/lib/python3/dist-packages/lutris in my case). Not entirely sure this is correct though.

**Comment by Albert1st1** [comment]
I also had it stopping at "Updating D9VK versions" on slackware64-current
`2020-03-21 13:53:10,139: Updating DXVK versions
Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/lutris/gui/application.py", line 173, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/lib64/python3.8/site-packages/lutris/gui/lutriswindow.py", line 102, in __init__
    self.game_store = self.get_store()
  File "/usr/lib64/python3.8/site-packages/lutris/gui/lutriswindow.py", line 315, in get_store
    game_store = GameStore(
  File "/usr/lib64/python3.8/site-packages/lutris/gui/views/store.py", line 133, in __init__
    self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'
2020-03-21 13:53:10,591: Updating D9VK versions`

Patching lutris/lutris/gui/views/store.py solved the start up problem.
`diff -ur lutris.orig/lutris/gui/views/store.py lutris/lutris/gui/views/store.py
--- lutris.orig/lutris/gui/views/store.py       2019-11-04 05:24:57.000000000 +0100
+++ lutris/lutris/gui/views/store.py    2020-03-21 14:14:07.776680005 +0100
@@ -130,7 +130,7 @@
         self.prevent_sort_update = False  # prevent recursion with signals
         self.modelfilter = self.store.filter_new()
         self.modelfilter.set_visible_func(self.filter_view)
-        self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
+        self.modelsort = Gtk.TreeModelSort.new_with_model(self.modelfilter)
         self.modelsort.connect("sort-column-changed", self.on_sort_column_changed)
         self.modelsort.set_sort_func(sort_col, sort_func, sort_col)
         self.sort_view(sort_key, sort_ascending)`

**Comment by agurenko** [comment]
Same problem with Fedora 32 Beta:

`$ lutris
2020-03-21 18:01:01,168: Running Lutris 0.5.4
2020-03-21 18:01:01,168: Using Intel
2020-03-21 18:01:01,168: Running Mesa driver 20.0.2 on Mesa Intel(R) HD Graphics 530 (SKL GT2) (0x191b)
2020-03-21 18:01:01,169: GPU: 10DE:134D 17AA:5050 using nouveau drivers
2020-03-21 18:01:01,169: GPU: 8086:191B 17AA:5050 using i915 drivers
2020-03-21 18:01:01,231: Vulkan is supported
2020-03-21 18:01:01,232: Updating DXVK versions
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/lutris/gui/application.py", line 173, in do_activate
self.window = LutrisWindow(application=self)
File "/usr/lib/python3.8/site-packages/lutris/gui/lutriswindow.py", line 102, in __init__
self.game_store = self.get_store()
File "/usr/lib/python3.8/site-packages/lutris/gui/lutriswindow.py", line 315, in get_store
game_store = GameStore(
File "/usr/lib/python3.8/site-packages/lutris/gui/views/store.py", line 133, in __init__
self.modelsort = Gtk.TreeModelSort.sort_new_with_model(self.modelfilter)
AttributeError: type object 'TreeModelSort' has no attribute 'sort_new_with_model'
2020-03-21 18:01:02,582: Updating D9VK versions`

**Comment by Steinhagen** [comment]
This issue was already fixed in the master branch:
https://github.com/lutris/lutris/commit/12a458db3c590c3f1972594e091a24cb4d65b610
Until a newer version is officially released, you can use the master branch to have Lutris up and running.

**Comment by ermin-sakic** [comment]
Can confirm, after updating from master I still have the following issue in 20.04:

```console

➜  lutris git:(master) lutris
2020-03-22 07:57:55,284: Migrating games field humblestoreid
2020-03-22 07:57:55,333: Running Lutris 0.5.4
2020-03-22 07:57:55,334: Running migration: d9vk_to_dxvk
2020-03-22 07:57:55,334: Using X.Org
2020-03-22 07:57:55,335: Running Mesa driver 20.0.0 on Radeon RX 580 Series (POLARIS10, DRM 3.35.0, 5.4.0-18-generic, LLVM 9.0.1) (0x67df)
2020-03-22 07:57:55,335: GPU: 1002:67DF 1682:C580 using amdgpu drivers
2020-03-22 07:57:55,355: Vulkan is supported
2020-03-22 07:57:55,356: Updating DXVK versions

(lutris:10698): Gtk-CRITICAL **: 07:57:55.391: Unable to retrieve object 'search_spinner' from class template for type 'LutrisWindow' while building a 'LutrisWindow'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/lutris-0.5.4-py3.8.egg/lutris/gui/application.py", line 168, in do_activate
    self.window = LutrisWindow(application=self)
  File "/usr/local/lib/python3.8/dist-packages/lutris-0.5.4-py3.8.egg/lutris/gui/lutriswindow.py", line 114, in __init__
    self.init_template()
  File "/usr/local/lib/python3.8/dist-packages/lutris-0.5.4-py3.8.egg/lutris/vendor/gi_composites.py", line 119, in <lambda>
    cls.init_template = lambda s: _init_template(s, cls, base_init_template)
  File "/usr/local/lib/python3.8/dist-packages/lutris-0.5.4-py3.8.egg/lutris/vendor/gi_composites.py", line 148, in _init_template
    raise AttributeError(
AttributeError: A missing child widget was set using GtkTemplate.Child and the entire template is now broken (widgets: main_box, register_button, search_entry, games_scrollwindow, search_toggle, zoom_adjustment, no_results_overlay, sidebar_revealer, sync_button, sidebar_scrolled, connection_label, search_spinner, connect_button, disconnect_button, search_revealer, sync_label, add_popover, sync_spinner, viewtype_icon, website_search_toggle)
```

Python 3.8.2 (default, Mar 13 2020, 10:14:16)

**Comment by ivanbalseirogarcia** [comment]
I also confirm, using Ubuntu Budgie 20.04 updated today, latest wine version from apt-get and launching lutris normal and sudo from cli does not open the application. Using a Ryzen 3 3200U system.
