### ISSUE TITLE
please make the scalable svg icon compatible with SVGTiny

### ISSUE THREAD

**Issue by sixsixfive** [lutris/lutris#296]
Qt both 4 and 5 only support SVGTiny 1.2 however the svg isn't compatible with this specification which results in very strange application icons on Qt-based desktops/panels/file managers.

SVG rendered in Qt
![svg-rendered-in-qt5](https://cloud.githubusercontent.com/assets/3780774/16177975/57daffb4-363c-11e6-9525-951fda5e8e32.png)

**Comment by strycore** [comment]
I have pushed an updated icon on the next branch which I generated using Inkscape "Plain SVG" export format. Can you tell me if this one is alright? (Can't test right now, I'm on a bus)

**Comment by sixsixfive** [comment]
no its still the same,  however I works if I ungroup all elements in inkscape:

working svg:

[lutris.svg.txt](https://github.com/lutris/lutris/files/323805/lutris.svg.txt)

**Comment by strycore** [comment]
Got the confirmation that it works fine, thanks a lot!
