### ISSUE TITLE
Detect presence of PS2 bios files

### ISSUE THREAD

**Issue by mYnDstrEAm** [lutris/lutris#3034]
It would be very useful if Lutris also carried out some configurations of runners after installing them from "Manage Runners" to make sure that they are a) well-configured for the system and b) work as in "plug&play" without any further setup required.

**System-dependent configuration**

For system-dependent configuration Lutris could detect information about for example installed graphics drivers, used hardware (graphics card, CPU) and more to make configurations to make the runner fit the system and run with good performance (these settings could later be automatically slightly altered depending on the game).

**Making sure the runner is set up properly and can run games**

Where automatic configuration isn't possible yet (without changes to external software) the user could be guided through a short setup after installing a runner.

It would be best if the Lutris project aggregated which necessary changes are required in different cases to automatically configure the runner/emulator and/or the system so that the runner is properly set up for running games.

One issue I had with the later was that when I installed PCSX2 via Lutris on one of my Debian10/KDE machines PCSX2 still needed two things to be configured in order to work instead of either, preferably, working right away or guiding the user through a setup:

* It still needed a PS2 BIOS rom (under Config->Plugin/BIOS Selector->BIOS)
* It did not have the GS plugin file (under Config->Plugin/BIOS Selector->Plugins) upon launching PCSX2 it said:

> The configured GS plugin file was not found
> [...]/lutris/runners/pcsx2/plugins/Please Configure
> Press Ok to go to the configuration panel

It may not be possible to automatically solve the first issue yet. This is why it would need a short setup process (which at first could be a simple message window asking the user to put file x in directory y to make sure the PS2 emulator works).

From #2285 it looked like I only needed to have libOpenGL0 installed - but I did have it installed on the machine. However, I did have the GS plugin file on another machine so I simply copied these two missing files from the other machine into the folder of the PCSX2 plugins ([...]/lutris/runners/pcsx2/plugins):

libGSdx-AV2.so

libGSdx-SSE4.so

As of right now, I don't know why these two files were present on one machine but not the other / how I got them onto the machine. Maybe this is something that could be automatically configured. And if it can't yet please show a short setup that tells the user what the problem is and how to solve it to make it easy to set up the runners.

These two issues reappeared on the machine from where I copied the files after updating Lutris today.

**Comment by strycore** [comment]
> It would be very useful if Lutris also carried out some configurations of runners after installing them from "Manage Runners" to make sure that they are a) well-configured for the system and b) work as in "plug&play" without any further setup required.


This is what Lutris is supposed to do, you ran into an issue for one runner. No need to consider the whole project broken because of the issue you ran into.

**Comment by mYnDstrEAm** [comment]
Okay, that's great then. Sorry for being not more specific about the PCSX2 issue.
I'll try to investigate why this happened further and update the issue if I find out. However, whenever I installed PCSX2 with Lutris the two things listed above had to be configured and were not shown in some kind of setup or message window after installing the runner. So maybe things could be made easier for users this way. I (intentionally) assumed other runners to potentially have similar issues based on this and that it does not carry out a system-dependent configuration that configures many of the graphics settings depending on many system-variables because some games did not work well with the preconfigured settings.
Thanks for clarifying.

**Comment by strycore** [comment]
There are 2 different things indeed. First is that we need a BIOS check for PS2. We have one for other consoles but we need to make it more generic so it's usable across all emulators.
Then there's a packaging issue in the PCSX2 runner itself. I think I gave this a look a while ago and couldn't figure out a fix. I should give it another look.

**Comment by strycore** [comment]
I have released a build of the most recent devel version of PCSX2. With the correct libraries installed locally, the GL plugin works without issue. The runner will display a message when libraries are not detected (tracked in #3083 ).
I still want to add a BIOS check, even if the emulator has one integrated.

**Comment by alx242** [comment]
I still don't get any GL plugins installed when I installed this runner. Is there some dependency that is required for it?

**Comment by legluondunet** [comment]
We could give a message to user when they install runner and PS2 bios are not present:

**_PCSX2 needs bios files to emulate PS2 games.
Needed bios files:
SCPH-70004_BIOS_V12_EUR_200.BIN
SCPH-70004_BIOS_V12_EUR_200.EROM
SCPH-70004_BIOS_V12_EUR_200.ROM1
SCPH-70004_BIOS_V12_EUR_200.ROM2
You need to place this files in ~/.PCSX2_**

It is just an example based on Retroarch doc, exact files names need to be verified and message improved.

@stryder: where do we have to add code and include verification? runner/pcsx2.py ?

**Comment by strycore** [comment]
@legluondunet check out the file `lutris/util/retroarch/core_config.py`. This is where I've started writing down BIOS list and hashes. In the case of PCSX2, it can be both a standalone emulator or a retroarch core so we would need to have some shared code to handle both.

**Comment by wrightgabriel0220** [comment]
This seems like it'd be pretty easy to extend the fix from https://github.com/lutris/lutris/pull/5807 to this. Gonna take a shot at this.

**Comment by wrightgabriel0220** [comment]
@strycore PCSX2 doesn't seem to store the full list of filenames and hashes anywhere in the same way Retroarch does with its info files. We have the list available at the emulation wiki link in my comment above, so I could basically copy all that info into a static file given I don't think the list of PS2 bios files available will change any time soon lol

Any given game on PCSX2 requires, at minimum, the main `ps2-0xxxr-ddddddddd.bin`-style main bios file. Old stuff can run on the newer versions, but not all new things can run on the older versions. Couldn't find a dedicated comprehensive list of what games require which BIOS so this may have to be left up to user experimentation. (as in there's no way to definitively tell a user "oh you need this BIOS". moreso just "that didn't work, your BIOS might be outdated") Trying right now to figure out if there's a way to tell the region of a game when launching it, since then we could at least ask the user for a specific region, but it's quite likely this ends up just being "stick the comprehensive list of BIOS files in a .info file or some other static resource, check that against the user's cache, pull everything that *is* available, and let PCSX2 report the issue to the user if the BIOS they tried doesn't work.

**Comment by strycore** [comment]
that's to be expected. for most runners, we'll have to maintain our own list of bios checksums. The best place to do that would be in the website's API but until this is done, it's fine to store bios info in a JSON in the lutris client.

**Comment by legluondunet** [comment]
should be fixed in 0.5.20 beta
