### ISSUE TITLE
PCSX2 runner not working anymore after adding Vulkan support: error while loading shared libraries: libgobject-2.0.so.0: wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by mYnDstrEAm** [lutris/lutris#3083]
PCSX2 did run fine previously. Since then I have added Vulkan support. Before adding Vulkan support error messages in the console and a message window said:
```
Missing vulkan libraries
Lutris was unable to detect Vulkan support for the i386 and x86_64 architecture.
This will prevent many games and programs from working.
To install it, please use the following guide: Installing Graphics Drivers
```
Link: [Installing Graphics Drivers](https://github.com/lutris/docs/blob/master/InstallingDrivers.md)

I already tried removing the runner and installing it again. The other runners like Dolphin are still working fine.

I get this error in the console when I try to start a game (which worked previously) with PCSX2 after "Game is considered started." and before "Game is considered exited.". The PCSX2 runner also doesn't start when clicking its play button due to the same error.

I followed the guide linked above and [solved an error I got by running this](https://askubuntu.com/questions/386281/error-while-loading-shared-libraries-libglu-so-1): `sudo apt-get install libglu1-mesa:i386`

`vulkaninfo` first line of output is: `ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_intel.so: wrong ELF class: ELFCLASS32`

[libglib2.0-0](https://packages.debian.org/cgi-bin/search_contents.pl?word=libgobject-2.0.so.0&searchmode=searchfiles&case=insensitive&version=unstable&arch=i386) is installed (2.58.3)
Lutris 0.5.7.1
Debian10/KDE (stable)
64bit

**Comment by byte1024** [comment]
What GPU do you have? I'm not seeing it.

Your GPU supports Vulkan and you installed the drivers correctly? Because it looks like one or the other isn't correct.

The error you get is standard. On Nvidia I get these errors:
$ vulkaninfo
ERROR: [Loader Message] Code 0 : /usr/lib/libvulkan_radeon.so: wrong ELF class: ELFCLASS32
ERROR: [Loader Message] Code 0 : /usr/lib/libvulkan_intel.so: wrong ELF class: ELFCLASS32

You need to post more info and double check the above questions.

Since vulkaninfo is failing the problem shouldn't be with Lutris.

**Comment by mYnDstrEAm** [comment]
In any case the guide seems to be wrong or incomplete as I followed the "AMD / Intel" steps and then got an error which I solved like described above. Afaik it should support Vulkan. PCSX2 is still running on another machine on which I haven't added Vulkan support. I'll investigate further...

**Comment by strycore** [comment]
find which package provides libgobject-2.0.so.0:

```
dpkg -S libgobject-2.0.so.0                                                                                     ─╯
libglib2.0-0:i386: /usr/lib/i386-linux-gnu/libgobject-2.0.so.0
libglib2.0-dev:amd64: /usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.3-gdb.py
libglib2.0-0:amd64: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6400.3
libglib2.0-0:i386: /usr/lib/i386-linux-gnu/libgobject-2.0.so.0.6400.3
libglib2.0-0:amd64: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
```

install the 32bit version:

```
sudo apt install libglib2.0-0:i386
```

This should solve the issue. Please reopen if is does not.

**Comment by mYnDstrEAm** [comment]
I did not solve the issue. I can't reopen the issue though.

The `dpkg -S` commands didn't nicely display which package I need to install so I entered the packages of the error messages into the link of "libglib2.0-0" of the original post above.

I had to install these packages:

sudo apt install libglib2.0-0:i386 libpng16-16:i386 libxrender1:i386 libxrandr2:i386 libxcb-shm0:i386 libxcb-render0:i386 liblzma5:i386 libudev1:i386 libpcap0.8:i386 libasound2:i386 libopengl0:i386 libgdk-pixbuf2.0-0:i386

I don't know if that's how it's supposed to be.

The first few packages were due to ELFCLASS errors in the console output. The later packages were due to these errors in PCSX2:

```
[wx] libudev.so.1: wrong ELF class: ELFCLASS64
[wx] libpcap.so.0.8: wrong ELF class: ELFCLASS64
[wx] libasound.so.2: wrong ELF class: ELFCLASS64
[wx] libOpenGL.so.0: wrong ELF class: ELFCLASS64
```

The last packages was due to this error in PCSX2:

```
(PCSX2:30508): GdkPixbuf-WARNING **: 15:33:17.286: Cannot open pixbuf loader module file '/usr/lib/i386-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/i386-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being. 
```

In PCSX2 I had problems with plugins again - 2 were missing and when I copied them in the SPU2 plugin was still missing despite being in the folder. I deinstalled the runner and installed it again. Then I copied the missing 2 dlls into the plugins folder. This made all plugins load (this is a separate issue.) PCSX2 now doesn't show any errors and does show "Plugins loaded successfully."

However, when trying to run a PCSX2 game which ran (albeit almost unusable; I also tried it with two other games of which one worked very well) before I get these errors in the console output of `lutris`:

```
Running /home/username/.local/share/lutris/runners/pcsx2/PCSX2 --fullscreen path-to-game.iso
Initial process has started with pid 8920
Game is considered started.
Gtk-Message:  Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Interface is initializing.  Entering Pcsx2App::OnInit!
Applying operating system default language...
Command line parsing...
Command line parsed!
(UserMode) Found portable install ini @ /home/username/.local/share/lutris/runners/pcsx2/portable.ini
Game is considered exited.
Initial process has exited.
All children have exited.
Exit with returncode 11
2020-08-17 15:50:47,024: Game still running (state: running)
```

Earlier I got this:

```
Command line parsed!
(UserMode) Found portable install ini @ /home/username/.local/share/lutris/runners/pcsx2/portable.ini
Game is considered exited.
All monitored processes have exited.
Never found the initial process' return code. Weird?
Exit with returncode 0
```

**Comment by strycore** [comment]
There is a new build available, please re-download the runner to try it out.

Once you have the latest PCSX2 build, go to the runner folder and type `ldd PCSX2 | grep -i "not found"`. This will tell you what libraries are missing.

Also do that for the plugins: `cd plugins; ldd *.so | grep -i "not found"`

One of the libraries I found out was needed by the GL plugin is EGL: `sudo apt install libegl1:i386`.
If you find other libraries required by PCSX2, please post them here. I'll configure the runner to check for those as well.

**Comment by mYnDstrEAm** [comment]
Great, it's working now! The pcsx2 games are running again.
Here's what I had to install on the machine with Vulkan support:
`sudo apt install libwx_baseu-3.0:i386 libwxbase3.0-0v5:i386  libwxgtk3.0-0v5:i386  libaio1:i386 libsdl2-2.0-0:i386  libportaudio2:i386  libsoundtouch1:i386`

I'll add the packages that were shown in ldd outputs on the machine without Vulkan support in a few minutes - I installed them but the games did run fine without them being installed.
