### ISSUE TITLE
Generating output-script fails: AttributeError: 'NoneType' object has no attribute 'play'

### ISSUE THREAD

**Issue by Ingwersaft** [lutris/lutris#3667]
Yesterday I was trying to setup [burrito](https://burrito.orthogonalprojects.com/) with my lutris Guild Wars 2 installation.

This requires to generate an output script, which fails:
```
~/Games/guild-wars-2$ lutris guild-wars-2 --output-script `pwd`/run_burrito_link.sh

2021-08-22 18:59:28,053: No cores found
Gtk-Message: 18:59:28.098: GtkDialog mapped without a transient parent. This is discouraged.
2021-08-22 18:59:28,098: Initializing lutris
2021-08-22 18:59:28,333: Downloading DXVK releases to /home/mk/.local/share/lutris/runtime/dxvk/dxvk_versions.json
2021-08-22 18:59:28,414: Writing to /home/mk/.local/share/lutris/runtime/dxvk/dxvk_versions.json
2021-08-22 18:59:28,416: Runtime updated. Initialization complete.
2021-08-22 18:59:28,419: Lutris 0.5.8.4
2021-08-22 18:59:28,420: Using NVIDIA drivers 460.91.03 for x86_64
2021-08-22 18:59:28,420: GPU: Quadro T2000
2021-08-22 18:59:28,421: GPU:   (evdi drivers)
2021-08-22 18:59:28,421: GPU:   (evdi drivers)
2021-08-22 18:59:28,422: GPU: 10DE:1FB8 1028:09C3 (nvidia drivers)
2021-08-22 18:59:28,422: GPU:   (evdi drivers)
2021-08-22 18:59:28,423: GPU:   (evdi drivers)
2021-08-22 18:59:28,423: GPU: 8086:9BF6 1028:09C3 (i915 drivers)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 423, in do_command_line
    self.generate_script(db_game, options.lookup_value("output-script").get_string())
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 275, in generate_script
    game.write_script(script_path)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 626, in write_script
    gameplay_info = self.get_gameplay_info()
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 387, in get_gameplay_info
    gameplay_info = self.runner.play()
AttributeError: 'NoneType' object has no attribute 'play'
2021-08-22 18:59:28,506: Shutting down Lutris

```

Any idea/workaround?
Thanks!

**Comment by strycore** [comment]
The game doesn't seem properly installed, it's missing the runner. I've fixed this situation by showing a proper error message instead of having this crash. On your end, make sure the game runs in lutris before generating a script.

**Comment by Ingwersaft** [comment]
The game runs perfectly fine using the lutris ui, so it is installed properly, but the script still fails.
