### ISSUE TITLE
Newly added Lutris games do not download their banners

### ISSUE THREAD

**Issue by danieljohnson2** [lutris/lutris#3957]
### Bug description

Lutris's banner and icon download is full of holes; it tries to download banners and icons when adding games or searching, but its spotty and games are easily introduced with no banner. They just come out at grey boxes.  

This could be considered a dupe of #3458, but I've got a repro for you. It's not just "I'd like a better architecture"- the current approach fails in some cases. Not just obscure cases either. Read on!

### How to Reproduce

First, go to Lutris.net and sign it, pick a game with a banner that you don't have, and add it to your library.

Now, open Lutris, and click the reload button on the Lutris sidebar row. Wait for it to complete.

Now, view the Lutris games and search for your new game. Don't forget to show non-installed games.

Your new game should appear, but it has no banner.

### Expected behavior

The banner should appear on the newly added game.

I had hoped for Lutris to download the banners for games that need them if missing, no matter how you add the game.

### Log output

```shell
INFO     2021-12-29 10:10:48,924 [startup.check_driver:53]:Using NVIDIA drivers 470.86 for x86_64
INFO     2021-12-29 10:10:48,924 [startup.check_driver:57]:GPU: NVIDIA GeForce RTX 3060
INFO     2021-12-29 10:10:48,924 [startup.check_driver:73]:GPU: 10DE:2503 196E:1377 (nvidia drivers)
DEBUG    2021-12-29 10:10:49,110 [lutriswindow.update_store:451]:Showing 184 games
DEBUG    2021-12-29 10:10:51,240 [base.wipe_game_cache:265]:Deleting lutris cache /home/danj/.cache/lutris/lutris
DEBUG    2021-12-29 10:10:51,240 [base.wipe_game_cache:113]:Deleting games from service-games for lutris
DEBUG    2021-12-29 10:10:51,259 [http.get:81]:GET https://lutris.net/api/games/library/danieljohnson2
DEBUG    2021-12-29 10:10:54,195 [lutris.load:108]:Matching with already installed games
DEBUG    2021-12-29 10:10:54,466 [lutris.load:111]:Lutris games loaded
DEBUG    2021-12-29 10:10:54,472 [lutriswindow.update_store:451]:Showing 185 games
INFO     2021-12-29 10:10:58,466 [application.do_shutdown:631]:Shutting down Lutris
```

### System Information

```shell
[System]
OS:              Pop!_OS 21.10 impish
Arch:            x86_64
Kernel:          5.15.8-76051508-generic
Desktop:         GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 5800X 8-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             31.4 GB
Swap:            0.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3060/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 470.86
OpenGL Core:     4.6.0 NVIDIA 470.86
OpenGL ES:       OpenGL ES 3.2 NVIDIA 470.86
Vulkan:          Supported
```

### Media (optional)

![Screenshot from 2021-12-29 10-15-45](https://user-images.githubusercontent.com/6507403/147677301-a0475c45-c2af-4620-a435-85dcca5e5374.png)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by Casul51** [comment]
Have exactly same issue.

**Comment by daishishi** [comment]
I believe I have the same issue, not sure. The banner when selecting the 'proper' Source appears alright, but in the **Games** source the banner is grey.
On the screenshot I attached the games: *Relic Hunters* and *Gibbous* appear under Steam and GOG respectively, but not in the **Games** library.
![Lutris banner](https://user-images.githubusercontent.com/7233354/151023930-705ef6e8-e320-4f8c-a48c-8c3a30226cf8.png)

**Comment by strycore** [comment]
fixed.

**Comment by danieljohnson2** [comment]
I'm afraid this still reproduces just as before.

Notice, the idea is to add the game to your library on Lutris.net, that is to say, using a web-browser. Then you reload the client so it sees the new game. This is not a search of Lutris.net done inside the Lutris client; the search must be done outside of it.

**Comment by aflyingpumpkin** [comment]
One solution could be to add an option on the right click menu / config menu for a game to download banners.

**Comment by strycore** [comment]
The banner would get downloaded if you refreshed the lutris service, which you need to press in order to get a new game from the library to the client

**Comment by danieljohnson2** [comment]
I assure you I retried my repro and it *did* repro again, just yesterday.

I used the sidebar button that has a "Reload" tooltip, and I see that it is called the "refresh" in the code. But it did not load any new banners. If it should, I can't see what code in there it supposed to be doing it.

It does not do what you think it does. It's bugged.
