### ISSUE TITLE
lutris reporting wrong wine version

### ISSUE THREAD

**Issue by duarm** [lutris/lutris#4180]
### Bug description

Hello, I 'm using wine-ge-custom, which is a fork of Valve's wine, installed from here https://aur.archlinux.org/packages/wine-ge-custom

Lutris detects this version as wine-5.12-13989-gca3681631ad, which is incorrect, since this build of wine is up to date with valve's wine, which is on version 7.0 of wine.

Quoting loathingkernel (the package maintainer)
> @endlesik It is not the package but the sources, wine-ge-custom has been rebased on Valve's wine fork instead of upstream wine, and the later tags do not exist in their repository.
> 
> To be exact the version is wine-5.12-13989-gca3681631ad, which means that it is 13989 commits after version 5.12, which aligns with the version 7.0 reported by winecfg and wineserver -v. Why tools like lutris are being silly and base their version checking on wine and not wineserver is beyond me. The version in wine is derived by the build-system from the repository information at build-time, where wineserver version is set by the developers.

### How to Reproduce

1. Install the wine-ge-custom found here https://github.com/GloriousEggroll/wine-ge-custom
2. In Lutris, the wrong version is listed on the Runner Options > Wine Version

### Expected behavior

Lutris should detect the correct version as returned by winecfg and wineserver -v, the incorrect version makes lutris erroneously think it can't use features like Esync and Fsync, since they were introduced in later versions of wine.

### Media (optional)

![image](https://user-images.githubusercontent.com/26150581/161287730-e05787d6-e266-4d26-bf00-a7681d7acae5.png)
![image](https://user-images.githubusercontent.com/26150581/161287831-abda4330-b392-44fb-ae8a-359e288e0014.png)

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
This is fixed in 7.2, see: https://github.com/lutris/wine/issues/141

**Comment by duarm** [comment]
This is not fixed, I'm using wine-ge-custom, which is based on Valve's wine, not lutris wine, the problem is that the correct version is returned by wineserver -v, not by wine --version
