### ISSUE TITLE
Cannot edit or remove games using right click

### ISSUE THREAD

**Issue by faedy2** [lutris/lutris#4340]
The right click context menu no longer appears in the Lutris UI

**Comment by battlegroundspng** [comment]
That's a plain ordinary jumplist. It shows recent games, recently played, recently installed. This list has no idea you've uninstalled a game.
You can right-click a game there to remove it from that list or pin a game to that list, in case you don't want that particular game to get flushed down.
[Battlegrounds Png](https://www.battlegroundspng.com)

**Comment by danieljohnson2** [comment]
A bug like that probably will show up in the Lutris debug log. Please run 'lutris -d' and try the context menu, and then post the log output produced.

**Comment by faedy2** [comment]
`Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/views/base.py", line 52, in popup_contextual_menu
    self.contextual_menu.popup(event, game_actions)
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/contextual_menu.py", line 53, in popup
    displayed = game_actions.get_displayed_entries()
  File "/usr/lib/python3/dist-packages/lutris/game_actions.py", line 141, in get_displayed_entries
    and not steam_shortcut.all_shortcuts_set(self.game)
  File "/usr/lib/python3/dist-packages/lutris/util/steam/shortcut.py", line 48, in all_shortcuts_set
    shortcut_found = [
  File "/usr/lib/python3/dist-packages/lutris/util/steam/shortcut.py", line 50, in <listcomp>
    if game.name in s['AppName']
KeyError: 'AppName'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 399, in update_revealer
    self.game_bar = GameBar(game, self.game_actions, self.application)
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/game_bar.py", line 61, in __init__
    self.update_view()
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/game_bar.py", line 86, in update_view
    self.play_button = self.get_play_button()
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/game_bar.py", line 226, in get_play_button
    popover = self.get_popover(self.get_game_buttons(), popover_button)
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/game_bar.py", line 233, in get_game_buttons
    displayed = self.game_actions.get_displayed_entries()
  File "/usr/lib/python3/dist-packages/lutris/game_actions.py", line 141, in get_displayed_entries
    and not steam_shortcut.all_shortcuts_set(self.game)
  File "/usr/lib/python3/dist-packages/lutris/util/steam/shortcut.py", line 48, in all_shortcuts_set
    shortcut_found = [
  File "/usr/lib/python3/dist-packages/lutris/util/steam/shortcut.py", line 50, in <listcomp>
    if game.name in s['AppName']
KeyError: 'AppName'`

> A bug like that probably will show up in the Lutris debug log. Please run 'lutris -d' and try the context menu, and then post the log output produced.

**Comment by danieljohnson2** [comment]
That is odd. The formatting that is- there used to be a sort of form you could fill out with a place to put the log that took care of that. It's gone. I wonder where it went.

However, that trace-back looks like issue #4195, which was fixed in version 0.5.10.1. I guess maybe you are running an earlier version.

**Comment by faedy2** [comment]
Bizarre
Maybe it's an issue with Pop_OS!
I have been updating my system periodically, but I still encounter this issue

**Comment by danieljohnson2** [comment]
The fix went in for 0.5.10.1, so you don't have it.

I've noticed that the usual packagers do not seem to have shipped this version. I don't know why; seems odd.

**Comment by hoxu** [comment]
[The Debian repository](https://download.opensuse.org/repositories/home:/strycore/Debian_11/all/) version is also suffering from this, as it's missing 0.5.10.1.
