### ISSUE TITLE
Lutris just uses its own wine version instead of the one configured

### ISSUE THREAD

**Issue by 5h4d** [lutris/lutris#4370]
In theory you can set a wine version to be used with all games in the runner options, however Lutris completely ignores this when installing a game with the "Install a Windows game from media" option; instead of using the specified version, it downloads whatever the latest lutris binary is. I understand how this can be useful as a default setting but not allowing people to change it is very annoying and borderline hostile.
![image](https://user-images.githubusercontent.com/62404657/178152148-1ded9477-60f0-4d39-b185-070e107edb95.png)

**Comment by belkka** [comment]
The same issue on Arch Linux (lutris 0.5.10.1-2). Whenever I start installing any game lutris downloads wine-lutris-7.2(...).tar.gz (latest of "wine lutris"), no matter which wine version is selected in preferences

**Comment by bell07** [comment]
Looked into code. `get_runners_to_install(self):`

[version = self._get_runner_version()](https://github.com/lutris/lutris/blob/master/lutris/installer/interpreter.py#L221) returns None, because no version is specified in installer script.

[default_wine = runner.get_runner_version() or {}](https://github.com/lutris/lutris/blob/master/lutris/installer/interpreter.py#L226): The method `runner.get_runner_version()` get online list and return the default version as defined at lutris.net

The step is missed to read the default version from runner settings.

**Comment by bell07** [comment]
I see the value to use always newest wine version. But in my use-case I prefer to use the system-wine as default, if nothing specified.

Maybe additional parameter "Prefer local default instead of newest wine for new installations"? Or an option to select wine before installation if no version is specified in json file?

**Comment by palexdev** [comment]
This is so annoying because the version used by Lutris is so old it gives me issues with any script I'm trying to install

**Comment by danieljohnson2** [comment]
I touch this with some trepidation, as I got reverted last time I tried to fix this. But this is a perennial problem, and while @strycore never told me what I had broken last time, I was then trying to apply the *entire* runner config during installation. Lots of room for that to go wrong.

But it's clear to me that everybody expects the runner config to apply to installers, and sometimes people need a funny WINE version to install something.

This time I will be more incremental. I've done a fix to *just* use the runner config's WINE version, no other setting, and *only* for WINE.

Please download the master branch and try it. No need to install; just run the 'bin/lutris' script you get, and see if setting the runner config to have the right WINE version makes your game install better.

**Comment by viirin** [comment]
I have been experiencing the same issue. I tried downloading the master branch a few minutes ago and ran the bin/lutris script. It's unfortunately not made any difference for me.

**Comment by danieljohnson2** [comment]
Nertz. It should worked.

@viirin, may I ask which WINE version you were trying to use for installation exactly? And which game you were installing?

**Comment by viirin** [comment]
In this case I was just trying to keep it set to the system version, which is 8.1 (Staging)

I've been attempting to install HorizonXI (FFXI private server) using the script here:

https://github.com/sarca571ca/horizonxi-lutris/blob/master/Horizon-XI.yaml

**Comment by danieljohnson2** [comment]
Ah, that is what I missed- using the system wine version.

I've given this a once over and it can now install using the system WINE for me.

Please download the even more latest master branch, and try again.

**Comment by PixsaOJ** [comment]
Why is this closed? Is it resolved?

**Comment by danieljohnson2** [comment]
This should now be fixed, and the fix should be in the next release of Lutris.

**Comment by zeus86** [comment]
can someone be more verbose regarding this? for me on arch with lutris 0.5.12 this is not fixed. when imanually add a custom bleeding edge proton-version it is recognized by lutris, and i can set it to default, but scripts from the lutris-website, that don't require a specific version (like "ea-app") just default to the latest included wine-version in lutris. the drop-dwon menu also flags the shipped version as "default". I wonder why i can edit this setting globally in the first place, when it is not recognized at all.

**Comment by danieljohnson2** [comment]
The next release of Lutris is 0.5.13, and there's [a beta out](https://github.com/lutris/lutris/releases/tag/v0.5.13-beta2)

This new Lutris should run installations with the version of WINE that you configure in the runner settings for WINE (found in the Preferences).

If you don't want to install beta 2, you could also download the source code, extract it, and run the bin/lutris script found within. You should be able to run installations like that.

**Comment by zeus86** [comment]
unfortunately beta2 is not yet reflected in the aur-package `lutris-git`, but what change actually made this work? at least i can't find something describing this bug in the changelogs of beta2 or beta1...

**Comment by danieljohnson2** [comment]
Those change-logs don't list bug-fixes. That's tracked right here.

As you can see above, it was commit e74754e6ffdfab935f77f0c43641877850fb4288; there were some later commits that are relevant, but that's the essential one.

**Comment by zeus86** [comment]
i see. thanks for the explanation. 
i manually edited the aur-pkginstall-script to install beta2. so far so good. the spinning gear looks funny btw. however, when i install my app (ea-app in this case), i do see messages referring to the default (lutris) wine-prefix, but after the app has been installed, at least the settings of the game showcase the previously choosen default. i'll try if this makes a difference in the game i want to install inside the ea-launcher, but at least it seems to have somewhat worked so far.
