### ISSUE TITLE
Amazon Prime Gaming shows a lot of games several times

### ISSUE THREAD

**Issue by NoXPhasma** [lutris/lutris#4451]
Affected Lutris versions: 0.5.11 & https://github.com/lutris/lutris/commit/686e475f9e28a58ee53b64c0563d7b6b2de7c47c 
Distribution: Arch Linux

After connecting my Amazon account and pulling my games, I have a lot of games which are being displayed two or even three times in the game list. I've already tried to remove my account and connect it again, but it keeps adding the same games several times.

Here's an example, there are many more:
![grafik](https://user-images.githubusercontent.com/7719590/187044802-12af9fd4-4285-49cd-9c01-a78347dbd872.png)

**Comment by tinglyowl** [comment]
_Yeah i agree_

**Comment by legluondunet** [comment]
Please install latest Lutris beta, should be fixed now.

**Comment by NoXPhasma** [comment]
Installed the 0.5.13 beta, disconnected my Amazon account, reconnected it, and it still shows many games more than once:

![grafik](https://user-images.githubusercontent.com/7719590/232500801-828d089f-97be-495a-bbd7-fd8dac9ba04a.png)

**Comment by NoXPhasma** [comment]
Maybe it helps if I can show what games are shown more than once for me. It's a lot of games:

Title (number of times being shown)
- 10 Seconds Ninja (2)
- A Normal Lost Phone (2)
- Automachef (2)
- Baseball Stars 2 (2)
- Bomber Crew (2)
- Darkside Detective (2)
- Deadlight: Director's Cut (2)
- Dear, Esther (2)
- Death Squared (2)
- Fatal Fury Special (3)
- Hue (2)
- Manual Samuel (2)
- Metal Slug 2 (3)
- Mugsters (2)
- Overcooked! (2)
- Planet Alpha (2)
- Pulster (2)
- Pumped BMX Pro (3)
- Samurai Showdown II (3)
- Serial Cleaner (3)
- Smoke and Sacrifice (2)
- Snake Pass (2)
- Stealth Bastard Deluxe (2)
- Swim Sanity (2)
- Sword Legacy Omen (2)
- The Escapists (2)
- The Flame In The Flood (2)
- The King of Fighters 2000 (2)
- The King of Fighters 2002 (2)
- The Last Blade (2)
- The Little Acre (2)
- The Metronomicon (2)
- Turmoil (2)
- The Twinkle Star Sprites (2)
- When Ski Lifts Go Wrong (2)
- Yoku's Island Express (2)
- Yooka-Laylee (2)

**Comment by legluondunet** [comment]
@danieljohnson2 an idea about this issue? I can not reproduce it but I own only two amazon games.

**Comment by danieljohnson2** [comment]
I do not have an Amazon account to test this with, so you are better off than I @legluondunet.

I know that there were problems with some games, because the query for patches needed to be split into numerous individual requests- not too many files at once. But this part of the code works differenly.

Best thing I can think of is to just de-duplicate the results that come back. Let me look at this.

**Comment by danieljohnson2** [comment]
OK, I've made a stab at deduping the games.

@NoXPhasma, please download [this branch here](https://github.com/lutris/lutris/tree/dj/amazon_repetition_amazon_repetition). Run the bin/lutris script therein, and then reload your Amazon library.

If it works, your old Amazon library will be deleted and the new one will be deduped. *Hopefully* any installed games will be fine.

**Comment by danieljohnson2** [comment]
Hmm, I can't explain that seg fault. But if that update didn't work, I think it means Amazon is sending the same game multiple times *with different IDs*. Surely these games are not really the same.

So, @NoXPhasma, if you are up for it, please try [that same branch](https://github.com/lutris/lutris/tree/dj/amazon_repetition_amazon_repetition).

Logging out and in again should be sufficient.

I've modified it to dump out all the Amazon library responses to the log, so I expect to get a biiiig log, but if you can get that to me, I may be able to figure this out.

If it's too big, maybe edit to down to one or two of the repeated games- but include each instance of the offending games, so we can see what differs between them.

Thanks, in advance, for you help.

**Comment by NoXPhasma** [comment]
Here you go: https://gist.github.com/NoXPhasma/3e79826a36f09f92d8a267beed1ff5c4

The only information I edited out was `channelId`. It was on each request the same, and I don't know if it is anything unique to my account.

**Comment by danieljohnson2** [comment]
OK, I see *three* keys in there, but most everything else in the data is the same. My research suggests that the right key is the ASIN, but existing user installs will be using the 'id' instead.

I've added code to dedup the game list *by ASIN*; we pick the smallest 'id' for our key, which is compatible with your installed games if you didn't install the wrong one of the duplicates.

@NoXPhasma, please try [that same branch](https://github.com/lutris/lutris/tree/dj/amazon_repetition_amazon_repetition) once again. Login and logout and hopefully your duplicates should be gone.

If you had installed a duped game, the installed game may lose their link to the service version of a game, but I think 
that's the lesser evil.

I do not really think this will help with the segfault though. I expect that's unrelated.

**Comment by NoXPhasma** [comment]
Yes, this fixed the multiple entries :+1: 

About the crash on update, I don't know why that happens, it happens since the first time Amazon Games was implemented. It basically does the same as it does when I login. It collects the games and then it segfaults. However, that's a different problem and should be looked at in a separate issue.

**Comment by danieljohnson2** [comment]
Good; I'll merge the de-duplication thing.

However, I've added some more logging to [that damn branch](https://github.com/lutris/lutris/tree/dj/amazon_repetition_amazon_repetition).

Perhaps you could try that real quick and post the log stuff (the big game list is no longer there). This will give me some idea about where it is crashing.

**Comment by NoXPhasma** [comment]
```
2023-04-18 10:29:39,528: Requesting library data 1
2023-04-18 10:29:39,528: Requesting library data 2
2023-04-18 10:29:40,529: Got next token in response, making next request
2023-04-18 10:29:40,530: Requesting library data 1
2023-04-18 10:29:40,530: Requesting library data 2
2023-04-18 10:29:41,891: Got next token in response, making next request
2023-04-18 10:29:41,891: Requesting library data 1
2023-04-18 10:29:41,891: Requesting library data 2
2023-04-18 10:29:42,796: Got next token in response, making next request
2023-04-18 10:29:42,796: Requesting library data 1
2023-04-18 10:29:42,796: Requesting library data 2
2023-04-18 10:29:43,634: Got next token in response, making next request
2023-04-18 10:29:43,634: Requesting library data 1
2023-04-18 10:29:43,634: Requesting library data 2
2023-04-18 10:29:44,535: Got next token in response, making next request
2023-04-18 10:29:44,535: Requesting library data 1
2023-04-18 10:29:44,535: Requesting library data 2
2023-04-18 10:29:45,387: Got next token in response, making next request
2023-04-18 10:29:45,387: Requesting library data 1
2023-04-18 10:29:45,393: Requesting library data 2
2023-04-18 10:29:46,241: Got next token in response, making next request
2023-04-18 10:29:46,241: Requesting library data 1
2023-04-18 10:29:46,241: Requesting library data 2
2023-04-18 10:29:47,099: Got next token in response, making next request
2023-04-18 10:29:47,099: Requesting library data 1
2023-04-18 10:29:47,099: Requesting library data 2
2023-04-18 10:29:47,785: Unable to get games library

(lutris:1433701): Gtk-WARNING **: 10:29:47.786: ../gtk/gtk/gtktreemodel.c:2507: bad row reference, proxy has no outstanding row references
[1]    1433701 segmentation fault  bin/lutris
```

**Comment by danieljohnson2** [comment]
Thanks; that's some suggested data. I'll do some tests. But I'll merge the branch first.

**Comment by danieljohnson2** [comment]
'Kay. Perhaps you could try [the branch](https://github.com/lutris/lutris/tree/dj/amazon_repetition_amazon_repetition) again. This time *reload*.

I've removed some bogus exception swallowing- it may still crash but I'm hoping for a real error report this time. You may even see it on screen.

**Comment by danieljohnson2** [comment]
Err... that was unexpected.

Did you try it more than once? Maybe it does not always fail and you just got lucky? Does it work now in the master branch, or the latest beta?

I mean, I'll take the fix - exception swallowing is Just Wrong anyway- but it should have reported an error *somewhere* at least.

**Comment by NoXPhasma** [comment]
Good call, the very next try it crashed again. But no error message is showing up. Tried it several times, and now it crashes reliably as before. Again, no error message. Only showing that it segfaults.

**Comment by danieljohnson2** [comment]
Get I get the debug log when it crashes?

**Comment by NoXPhasma** [comment]
Where can I find that debug log?

**Comment by danieljohnson2** [comment]
It's the output of 'lutris -d'.

I am hoping it will be different this time.

**Comment by NoXPhasma** [comment]
Thanks. But it is not really helpful: https://gist.github.com/NoXPhasma/8572ae6b5b030df70223121df82e05bd

**Comment by danieljohnson2** [comment]
At least it is different, if not real helpful. The previous one showed a GTK corruption warning, suggesting there's something wrong we how we are populating the view. The new log seems to show it's populating the view when it crashes again.

If you reload Amazon without looking (ie, have the 'Games' view selected when you click the button) does that help?

**Comment by danieljohnson2** [comment]
Hmmm.

My day job is calling, but I'll come back to this later and try changing how we load the view during this processing.

'Ta.

**Comment by danieljohnson2** [comment]
OK, @NoXPhasma, I'm back and I think I've got it.

It's not Amazon at all; it's a Lutris bug that affects all services. Python really pampers programmers with its global interpreter lock- you hardly have to think about thread-safety at all. But GTK is another story, and you must take care not to touch it from any thread but the main thread.

Login/logout is okay, but 'Reload' breaks this rule, raising signals from a worker thread- and these trigger the view to reload. Doing this on the wrong thread corrupts GTK, which has little protection against it.

I've looked at this problem before and I'm embarrassed not to have seem it- it's *right there* plain as day.

Anyway, please try [that branch again](https://github.com/lutris/lutris/tree/dj/amazon_repetition_amazon_repetition). I'll wager your crash will be a thing of the past.

**Comment by NoXPhasma** [comment]
It indeed fixed the crash, nice find :)

**Comment by danieljohnson2** [comment]
Excellent, and thank you @NoXPhasma. That's two longstanding bugs down, and I couldn't have done it without your patient support.
