### ISSUE TITLE
Installations still fail

### ISSUE THREAD

**Issue by l0drex** [lutris/lutris#4541]
Whenever I try to install a program, the installation fails. Sometimes, the buttons become unresponsive and I have to kill Lutris and all wine processes from the system manager.

On current master, I get the following when installing Ubisoft Connect:

<details>
<summary>Logs</summary>

```
2022-10-04 12:45:54,318: Starting Lutris 0.5.11
2022-10-04 12:45:54,441: Using NVIDIA drivers 515.76 for x86_64
2022-10-04 12:45:54,441: GPU: NVIDIA GeForce GTX 1060 6GB
2022-10-04 12:45:54,441: GPU: 10DE:1C03 10DE:1C03 (nvidia drivers)
2022-10-04 12:45:54,560: Startup complete
2022-10-04 12:46:03,423: Getting runner information for wine
2022-10-04 12:46:06,280: All files available
2022-10-04 12:46:06,280: All files are available, continuing install
2022-10-04 12:46:06,283: Skipping caching of /home/l0drex/Downloads/ubisoft-connect/uplay/UbisoftConnectInstaller.exe, already cached in /home/l0drex/Downloads/ubisoft-connect/uplay
2022-10-04 12:46:06,284: Creating a win64 prefix in /home/l0drex/.games2/ubisoft-connect
2022-10-04 12:51:06,798: win64 Prefix created in /home/l0drex/.games2/ubisoft-connect
2022-10-04 12:51:06,879: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,879: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,879: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,879: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,879: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,879: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,879: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,880: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,880: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,880: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,880: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,900: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,900: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,935: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,936: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,936: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,936: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,936: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,941: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,941: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,941: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,941: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,941: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,942: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,942: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,942: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,942: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,942: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,949: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,949: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,949: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,949: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,949: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,954: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,954: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,955: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,955: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,955: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,959: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,959: Accessing game config while runner wasn't given one.
2022-10-04 12:51:06,959: The game doesn't have an executable
lutris-wrapper: /home/l0drex/.local/share/lutris/runtime/winetricks/winetricks
Started initial process 25811 from /home/l0drex/.local/share/lutris/runtime/winetricks/winetricks --unattended arial
Start monitoring process.
Executing mkdir -p /home/l0drex/.games2
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
WINEPREFIX INFO:
Drive C: insgesamt 0
drwxr-xr-x 1 l0drex l0drex  72  4. Okt 12:46 .
drwxr-xr-x 1 l0drex l0drex 126  4. Okt 12:46 ..
drwxr-xr-x 1 l0drex l0drex  18  4. Okt 12:46 ProgramData
drwxr-xr-x 1 l0drex l0drex 118  4. Okt 12:46 Program Files
drwxr-xr-x 1 l0drex l0drex  24  4. Okt 12:46 users
drwxr-xr-x 1 l0drex l0drex 342  4. Okt 12:46 windows

Registry info:
/home/l0drex/.games2/ubisoft-connect/system.reg:#arch=win64
/home/l0drex/.games2/ubisoft-connect/userdef.reg:#arch=win64
/home/l0drex/.games2/ubisoft-connect/user.reg:#arch=win64
------------------------------------------------------
------------------------------------------------------
warning: /home/l0drex/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message "" 
------------------------------------------------------
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
2022-10-04 12:51:07,960: Command exited with code 256
None

Process finished with exit code 130 (interrupted by signal 2: SIGINT)
```

</details>

I was able to install Ubisoft Connect by manually running the scripts from the yaml file. I am also able to add this installation manually and run it from Lutris.

**Comment by danieljohnson2** [comment]
So, those logs- did those come from the 0.5.11 release or the current master?

I had believed that the current master would no longer be giving you those "Accessing game config while runner wasn't given one.". If that's right, then presumably the "The game doesn't have an executable" thing is the issue.

Anyhoo, please try [this branch](https://github.com/lutris/lutris/tree/dj/exe_what_exe) and give us the log. This will put some extra stuff in the log with that error message, and may provide some insight.

**Comment by l0drex** [comment]
Yes, these are logs from the current master. From the exe_what_exe branch:

```
2022-10-05 15:47:34,754: Starting Lutris 0.5.11
2022-10-05 15:47:34,866: Using NVIDIA drivers 515.76 for x86_64
2022-10-05 15:47:34,867: GPU: NVIDIA GeForce GTX 1060 6GB
2022-10-05 15:47:34,867: GPU: 10DE:1C03 10DE:1C03 (nvidia drivers)
2022-10-05 15:47:35,033: Startup complete
2022-10-05 15:47:40,495: Getting runner information for wine
2022-10-05 15:47:41,393: All files available
2022-10-05 15:47:41,394: All files are available, continuing install
2022-10-05 15:47:41,396: Skipping caching of /home/l0drex/Downloads/origin/client/OriginSetup.exe, already cached in /home/l0drex/Downloads/origin/client
2022-10-05 15:47:41,397: Creating a win64 prefix in /home/l0drex/.games/origin
2022-10-05 15:52:41,910: win64 Prefix created in /home/l0drex/.games/origin
2022-10-05 15:52:41,958: Accessing game config while runner wasn't given one.
...
2022-10-05 15:52:42,020: Accessing game config while runner wasn't given one.
2022-10-05 15:52:42,020: The game doesn't have an executable
{'game_path': '/home/l0drex/.games', 'disable_runtime': False, 'prefer_system_libs': True, 'reset_desktop': False, 'gamescope': False, 'gamescope_output_res': False, 'gamescope_game_res': False, 'single_cpu': False, 'limit_cpu_count': '1', 'restore_gamma': False, 'disable_compositor': False, 'disable_screen_saver': True, 'reset_pulse': False, 'pulse_latency': False, 'use_us_layout': False, 'optimus': 'off', 'vk_icd': '/usr/share/vulkan/icd.d/nvidia_icd.json', 'mangohud': False, 'gamemode': False, 'prime': False, 'dri_prime': False, 'sdl_video_fullscreen': 'off', 'display': 'off', 'resolution': 'off', 'terminal': False, 'terminal_app': '/usr/bin/konsole', 'locale': '', 'prelaunch_wait': False, 'xephyr': 'off', 'xephyr_fullscreen': True}
{'version': 'lutris-7.2-2-x86_64', 'system_winetricks': False, 'dxvk': True, 'dxvk_version': 'v1.10.3', 'vkd3d': True, 'vkd3d_version': 'v2.6', 'd3d_extras': True, 'd3d_extras_version': 'v2', 'dxvk_nvapi': True, 'dxvk_nvapi_version': 'v0.5.4', 'dgvoodoo2': False, 'dgvoodoo2_version': 'v2.79.1', 'esync': True, 'fsync': True, 'fsr': True, 'battleye': True, 'eac': True, 'Desktop': False, 'Dpi': False, 'MouseWarpOverride': 'enable', 'Audio': 'auto', 'show_debug': '-all', 'ShowCrashDialog': False, 'autoconf_joypad': False, 'sandbox': True}
2022-10-05 15:52:42,020: Accessing game config while runner wasn't given one.
{}
  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/l0drex/Projekte/lutris/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/home/l0drex/Projekte/lutris/lutris/installer/commands.py", line 441, in task
    command = task(**data)
  File "/home/l0drex/Projekte/lutris/lutris/runners/commands/wine.py", line 358, in winetricks
    return wineexec(
  File "/home/l0drex/Projekte/lutris/lutris/runners/commands/wine.py", line 314, in wineexec
    command = MonitoredCommand(
  File "/home/l0drex/Projekte/lutris/lutris/command.py", line 79, in __init__
    self.cwd = self.get_cwd(cwd)
  File "/home/l0drex/Projekte/lutris/lutris/command.py", line 117, in get_cwd
    cwd = self.runner.working_dir if self.runner else None
  File "/home/l0drex/Projekte/lutris/lutris/runners/wine.py", line 539, in working_dir
    if self.game_exe:
  File "/home/l0drex/Projekte/lutris/lutris/runners/wine.py", line 521, in game_exe
    traceback.print_stack()
lutris-wrapper: /home/l0drex/.local/share/lutris/runtime/winetricks/winetricks
Started initial process 6412 from /home/l0drex/.local/share/lutris/runtime/winetricks/winetricks --unattended arial
Start monitoring process.
Executing mkdir -p /home/l0drex/.games
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
WINEPREFIX INFO:
Drive C: insgesamt 24
drwxr-xr-x  6 l0drex l0drex 4096  5. Okt 15:47 .
drwxr-xr-x  4 l0drex l0drex 4096  5. Okt 15:48 ..
drwxr-xr-x  3 l0drex l0drex 4096  5. Okt 15:47 ProgramData
drwxr-xr-x  6 l0drex l0drex 4096  5. Okt 15:47 Program Files
drwxr-xr-x  4 l0drex l0drex 4096  5. Okt 15:47 users
drwxr-xr-x 18 l0drex l0drex 4096  5. Okt 15:47 windows

Registry info:
/home/l0drex/.games/origin/system.reg:#arch=win64
/home/l0drex/.games/origin/userdef.reg:#arch=win64
/home/l0drex/.games/origin/user.reg:#arch=win64
------------------------------------------------------
------------------------------------------------------
warning: /home/l0drex/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message "" 
------------------------------------------------------
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
2022-10-05 15:52:43,022: Command exited with code 256
None
2022-10-05 15:52:54,353: Cancelling installation of Origin
2022-10-05 15:52:59,652: Shutting down Lutris

Process finished with exit code 0
```

**Comment by danieljohnson2** [comment]
I can see from this that my previous commit to eliminate "Accessing game config while runner wasn't given one." did not do enough. I will investigate.

**Comment by danieljohnson2** [comment]
OK, I've made a deeper effort to get the config data in there. Might help. It's committed to the same branch, please download again (or git pull) and try again, and lets see if it helped.

**Comment by danieljohnson2** [comment]
Oh crap, never mind. I committed all that to master. I'll revert it all and get back to you once I've done it over in the branch.

**Comment by danieljohnson2** [comment]
Okay, I've reapplied the commits to [the branch](https://github.com/lutris/lutris/tree/dj/exe_what_exe).

Please redownload or pull that, and give it a try. I'm not sure I'm on the right track, but it is worth a shot.

**Comment by l0drex** [comment]
I now see this:
```
2022-10-06 13:40:31,065: Starting Lutris 0.5.11
2022-10-06 13:40:31,173: Using NVIDIA drivers 515.76 for x86_64
2022-10-06 13:40:31,174: GPU: NVIDIA GeForce GTX 1060 6GB
2022-10-06 13:40:31,174: GPU: 10DE:1C03 10DE:1C03 (nvidia drivers)
2022-10-06 13:40:31,350: Startup complete
2022-10-06 13:40:36,139: Getting runner information for wine
2022-10-06 13:40:37,217: All files available
2022-10-06 13:40:37,217: All files are available, continuing install
2022-10-06 13:40:37,220: Skipping caching of /home/l0drex/Downloads/origin/client/OriginSetup.exe, already cached in /home/l0drex/Downloads/origin/client
2022-10-06 13:40:37,223: Creating a win64 prefix in /home/l0drex/.games/origin
2022-10-06 13:45:37,755: win64 Prefix created in /home/l0drex/.games/origin
2022-10-06 13:45:37,799: No template string given
2022-10-06 13:45:37,799: No template string given
  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/l0drex/Projekte/lutris/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/home/l0drex/Projekte/lutris/lutris/installer/commands.py", line 450, in task
    command = task(**data)
  File "/home/l0drex/Projekte/lutris/lutris/runners/commands/wine.py", line 358, in winetricks
    return wineexec(
  File "/home/l0drex/Projekte/lutris/lutris/runners/commands/wine.py", line 314, in wineexec
    command = MonitoredCommand(
  File "/home/l0drex/Projekte/lutris/lutris/command.py", line 79, in __init__
    self.cwd = self.get_cwd(cwd)
  File "/home/l0drex/Projekte/lutris/lutris/command.py", line 117, in get_cwd
    cwd = self.runner.working_dir if self.runner else None
  File "/home/l0drex/Projekte/lutris/lutris/runners/wine.py", line 539, in working_dir
    if self.game_exe:
  File "/home/l0drex/Projekte/lutris/lutris/runners/wine.py", line 521, in game_exe
    traceback.print_stack()
2022-10-06 13:45:38,400: The game doesn't have an executable
{'game_path': '/home/l0drex/.games', 'disable_runtime': False, 'prefer_system_libs': True, 'reset_desktop': False, 'gamescope': False, 'gamescope_output_res': False, 'gamescope_game_res': False, 'single_cpu': False, 'limit_cpu_count': '1', 'restore_gamma': False, 'disable_compositor': False, 'disable_screen_saver': True, 'reset_pulse': False, 'pulse_latency': False, 'use_us_layout': False, 'optimus': 'off', 'vk_icd': '/usr/share/vulkan/icd.d/nvidia_icd.json', 'mangohud': False, 'gamemode': False, 'prime': False, 'dri_prime': False, 'sdl_video_fullscreen': 'off', 'display': 'off', 'resolution': 'off', 'terminal': False, 'terminal_app': '/usr/bin/konsole', 'locale': '', 'prelaunch_wait': False, 'xephyr': 'off', 'xephyr_fullscreen': True}
{'version': 'caffe-7.18-x86_64', 'system_winetricks': False, 'dxvk': True, 'dxvk_version': 'v1.10.3', 'vkd3d': True, 'vkd3d_version': 'v2.6', 'd3d_extras': True, 'd3d_extras_version': 'v2', 'dxvk_nvapi': True, 'dxvk_nvapi_version': 'v0.5.4', 'dgvoodoo2': False, 'dgvoodoo2_version': 'v2.79.1', 'esync': True, 'fsync': True, 'fsr': True, 'battleye': True, 'eac': True, 'Desktop': False, 'Dpi': False, 'MouseWarpOverride': 'enable', 'Audio': 'auto', 'show_debug': '-all', 'ShowCrashDialog': False, 'autoconf_joypad': False, 'sandbox': True}
{'exe': '', 'working_dir': '', 'prefix': '/home/l0drex/.games/origin'}
lutris-wrapper: /home/l0drex/.local/share/lutris/runtime/winetricks/winetricks
Started initial process 7400 from /home/l0drex/.local/share/lutris/runtime/winetricks/winetricks --unattended arial
Start monitoring process.
Executing mkdir -p /home/l0drex/.games
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
WINEPREFIX INFO:
Drive C: insgesamt 24
drwxr-xr-x  6 l0drex l0drex 4096  6. Okt 13:40 .
drwxr-xr-x  4 l0drex l0drex 4096  6. Okt 13:41 ..
drwxr-xr-x  3 l0drex l0drex 4096  6. Okt 13:40 ProgramData
drwxr-xr-x  6 l0drex l0drex 4096  6. Okt 13:40 Program Files
drwxr-xr-x  4 l0drex l0drex 4096  6. Okt 13:40 users
drwxr-xr-x 18 l0drex l0drex 4096  6. Okt 13:40 windows

Registry info:
/home/l0drex/.games/origin/system.reg:#arch=win64
/home/l0drex/.games/origin/userdef.reg:#arch=win64
/home/l0drex/.games/origin/user.reg:#arch=win64
------------------------------------------------------
------------------------------------------------------
warning: /home/l0drex/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message "" 
------------------------------------------------------
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
2022-10-06 13:45:39,403: Command exited with code 256
None

Process finished with exit code 130 (interrupted by signal 2: SIGINT)
```

**Comment by danieljohnson2** [comment]
Still not there.

I've made one more tweak, trying to get a working_dir in there. Please grab it again and try again.

If this doesn't work, I must be on the wrong track.

**Comment by l0drex** [comment]
I don't see the `game has no executable` error anymore, but it still crashes:

```
/home/l0drex/Projekte/lutris/.venv/bin/python /home/l0drex/Projekte/lutris/bin/lutris 
2022-10-07 11:06:52,095: Starting Lutris 0.5.11
2022-10-07 11:06:52,191: Using NVIDIA drivers 515.76 for x86_64
2022-10-07 11:06:52,191: GPU: NVIDIA GeForce GTX 1060 6GB
2022-10-07 11:06:52,192: GPU: 10DE:1C03 10DE:1C03 (nvidia drivers)
2022-10-07 11:06:52,329: Startup complete
2022-10-07 11:07:00,553: Getting runner information for wine
2022-10-07 11:07:01,613: All files available
2022-10-07 11:07:01,613: All files are available, continuing install
2022-10-07 11:07:01,614: Skipping caching of /home/l0drex/Downloads/origin/client/OriginSetup.exe, already cached in /home/l0drex/Downloads/origin/client
2022-10-07 11:07:01,615: Creating a win64 prefix in /home/l0drex/.games/origin
2022-10-07 11:12:02,546: win64 Prefix created in /home/l0drex/.games/origin
2022-10-07 11:12:02,612: No template string given
lutris-wrapper: /home/l0drex/.local/share/lutris/runtime/winetricks/winetricks
Started initial process 5824 from /home/l0drex/.local/share/lutris/runtime/winetricks/winetricks --unattended arial
Start monitoring process.
Executing mkdir -p /home/l0drex/.games
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
WINEPREFIX INFO:
Drive C: insgesamt 24
drwxr-xr-x  6 l0drex l0drex 4096  7. Okt 11:07 .
drwxr-xr-x  4 l0drex l0drex 4096  7. Okt 11:07 ..
drwxr-xr-x  3 l0drex l0drex 4096  7. Okt 11:07 ProgramData
drwxr-xr-x  6 l0drex l0drex 4096  7. Okt 11:07 Program Files
drwxr-xr-x  4 l0drex l0drex 4096  7. Okt 11:07 users
drwxr-xr-x 18 l0drex l0drex 4096  7. Okt 11:07 windows

Registry info:
/home/l0drex/.games/origin/system.reg:#arch=win64
/home/l0drex/.games/origin/userdef.reg:#arch=win64
/home/l0drex/.games/origin/user.reg:#arch=win64
------------------------------------------------------
------------------------------------------------------
warning: /home/l0drex/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message "" 
------------------------------------------------------
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
2022-10-07 11:12:04,203: Command exited with code 256
None

Process finished with exit code 130 (interrupted by signal 2: SIGINT)
```

This might be interesting:
> `No template string given`

**Comment by danieljohnson2** [comment]
Well, crud. I'm all out of ideas.

Origin installs fine for me, so I can't reproduce the problem. Those "No template string given" messages are due to the sloppy way I implemented this- that's not the problem in itself.

But if it is not due to the "missing exe" - really missing working directory, the message is misleading- I have no idea what it might be.

Sorry I couldn't do better for you.

**Comment by l0drex** [comment]
When I set debug points at the command execution line, I get different results which makes it even more difficult to debug. The Arial installation gets a bit further, but still crashes.

**Comment by al12gamer** [comment]
Is this from the flatpak Lutris install or the Lutris install from your package manager?

**Comment by strycore** [comment]
I believe this should be fixed when using both latest versions of Lutris and lutris-GE-Proton8. If not let me know.
