### ISSUE TITLE
"Checking for runtime updates" appears every time

### ISSUE THREAD

**Issue by geajack** [lutris/lutris#4682]
The "Checking for runtime updates..." popup appears every time I start Lutris. Lutris is the only program on my computer that does this, and for good reason. I know it only takes a few seconds (although sometimes it feels like it takes more than a few...), but it's just annoying and not really something any piece of software should be doing to stall you arbitrarily everytime you want to use it. If it must check for updates automatically, I'd rather it happen in the background after the launcher is already running.

**Comment by danieljohnson2** [comment]
When I run Lutris, that dialog appears only on the first startup each day.

But this is strange; there's no code for that, it shows the dialog even where there's no work to do. I should fix that.

Updating in the background would be nice, but updating Lutris while it is running is tricky. Consider what happens on first run- nothing can work at first, and everything must be enabled as the runtime becomes available.

**Comment by danieljohnson2** [comment]
OK, I've improved the check on this so that dialog should never appear if no updates are due.

Updates seem to have various schedules; the most frequent are every 6 hours for WINE components. I don't know why that is, so I just left it like that.

These various schedules are probably why you saw inconsistent update times; sometimes it updates more things, sometimes fewer.

**Comment by geajack** [comment]
> When I run Lutris, that dialog appears only on the first startup each day.

Same here, now I check. Still not ideal user experience, though.

**Comment by strycore** [comment]
>  Lutris is the only program on my computer that does this

You don't have Steam?

**Comment by strycore** [comment]
Right now, we don't have an option to get rid of that startup window. Once we have a global download queue we will no longer need it.

Steam does have a similar window but it's for updating the Steam client itself. Proton and other Steam runtimes are downloaded from the same download queue as the games.
This is the approach I want to take for 0.6.0
