### ISSUE TITLE
Lutris can't launch a game, but I can launch it in a terminal

### ISSUE THREAD

**Issue by geajack** [lutris/lutris#4684]
I've been playing The Witness for a few days without issue on Lutris, but right now it just can't launch it for some reason. When I click "Launch", it just hangs while the button says "Launching". I end up just killing Lutris entirely. The logs are empty.

My settings:

![image](https://user-images.githubusercontent.com/2124157/210139223-a18e6095-872b-44e2-b7e3-5afe9e7ca50e.png)
![image](https://user-images.githubusercontent.com/2124157/210139229-fb414166-c45f-44bf-9ae1-a3e698a0ad55.png)

I went into a terminal to try and launch the game exactly how Lutris launches it:

```
jack@tower:~/Applications/Games/The Witness/drive_c/GOG Games/The Witness$ WINEPREFIX=/home/jack/Applications/Games/The\ Witness /home/jack/.local/share/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine64 witness64_d3d11.exe
```

And this works fine.

**Comment by danieljohnson2** [comment]
Give us the debug log. To do this, run "lutris -d" at the terminal and try your game. This will print lots of spam to the terminal; give us that output.

**Comment by geajack** [comment]
You got it:

```
jack@tower:~$ lutris -d
2022-12-31 14:14:08,687: Starting Lutris 0.5.9.1
2022-12-31 14:14:08,757: No cores found
2022-12-31 14:14:09,603: Failed to read content length on response from https://api.github.com/repos/lutris/dxvk/releases
2022-12-31 14:14:10,043: Failed to read content length on response from https://api.github.com/repos/lutris/dxvk-nvapi/releases
2022-12-31 14:14:10,450: Startup complete
INFO     2022-12-31 14:14:10,454 [startup.check_driver:53]:Using NVIDIA drivers 525.60.11 for x86_64
INFO     2022-12-31 14:14:10,454 [startup.check_driver:57]:GPU: NVIDIA GeForce RTX 3080
INFO     2022-12-31 14:14:10,455 [startup.check_driver:73]:GPU: 10DE:2216 196E:138B (nvidia drivers)
DEBUG    2022-12-31 14:14:10,804 [lutriswindow.update_store:451]:Showing 2 games
DEBUG    2022-12-31 14:14:16,144 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/dxgi.dll with DXVK version
DEBUG    2022-12-31 14:14:16,150 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3d11.dll with DXVK version
DEBUG    2022-12-31 14:14:16,157 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3d10core.dll with DXVK version
DEBUG    2022-12-31 14:14:16,162 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3d9.dll with DXVK version
DEBUG    2022-12-31 14:14:16,170 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/dxgi.dll with DXVK version
DEBUG    2022-12-31 14:14:16,178 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3d11.dll with DXVK version
DEBUG    2022-12-31 14:14:16,186 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3d10core.dll with DXVK version
DEBUG    2022-12-31 14:14:16,192 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3d9.dll with DXVK version
DEBUG    2022-12-31 14:14:16,201 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3d12.dll with VKD3D version
DEBUG    2022-12-31 14:14:16,202 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/nvapi64.dll with DXVK-NVAPI version
DEBUG    2022-12-31 14:14:16,202 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/nvml.dll with DXVK-NVAPI version
DEBUG    2022-12-31 14:14:16,202 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/nvapi.dll with DXVK-NVAPI version
DEBUG    2022-12-31 14:14:16,203 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/nvml.dll with DXVK-NVAPI version
DEBUG    2022-12-31 14:14:16,226 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/nvngx.dll with DXVK-NVAPI version
DEBUG    2022-12-31 14:14:16,227 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/_nvngx.dll with DXVK-NVAPI version
DEBUG    2022-12-31 14:14:16,227 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dcompiler_42.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,227 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dcompiler_43.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,228 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dcompiler_46.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,229 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dcompiler_47.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,229 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx10_33.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,229 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx10_34.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,230 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx10_35.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,230 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx10_36.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,231 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx10_37.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,232 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx10_38.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,232 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx10_39.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,233 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx10_40.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,233 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx10_41.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,234 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx10_42.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,234 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx10_43.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,234 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx10.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,235 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx11_42.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,235 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx11_43.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,235 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx9_24.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,236 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx9_25.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,236 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx9_26.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,236 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx9_27.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,237 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx9_28.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,237 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx9_29.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,238 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx9_30.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,238 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx9_31.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,239 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx9_32.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,239 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx9_33.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,239 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx9_34.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,240 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx9_35.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,240 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx9_36.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,241 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx9_37.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,241 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx9_38.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,241 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx9_39.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,241 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx9_40.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,242 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx9_41.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,242 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx9_42.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,242 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/system32/d3dx9_43.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,242 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dcompiler_42.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,243 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dcompiler_43.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,243 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dcompiler_46.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,243 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dcompiler_47.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,243 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx10_33.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,244 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx10_34.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,244 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx10_35.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,244 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx10_36.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,244 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx10_37.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,245 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx10_38.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,245 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx10_39.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,245 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx10_40.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,246 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx10_41.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,246 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx10_42.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,246 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx10_43.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,247 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx10.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,247 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx11_42.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,247 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx11_43.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,248 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx9_24.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,248 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx9_25.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,248 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx9_26.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,249 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx9_27.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,249 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx9_28.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,249 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx9_29.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,249 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx9_30.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,249 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx9_31.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,249 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx9_32.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,250 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx9_33.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,250 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx9_34.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,250 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx9_35.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,250 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx9_36.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,250 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx9_37.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,250 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx9_38.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,251 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx9_39.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,251 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx9_40.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,251 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx9_41.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,251 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx9_42.dll with D3D Extras version
DEBUG    2022-12-31 14:14:16,251 [dll_manager.enable_dll:131]:Replacing /home/jack/Applications/Games/The Witness/drive_c/windows/syswow64/d3dx9_43.dll with D3D Extras version
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/exceptions.py", line 57, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 420, in configure_game
    gameplay_info = self.get_gameplay_info()
  File "/usr/lib/python3/dist-packages/lutris/game.py", line 398, in get_gameplay_info
    gameplay_info = self.runner.play()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 825, in play
    launch_info = {"env": self.get_env(os_env=False)}
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 749, in get_env
    env = super(wine, self).get_env(False)
  File "/usr/lib/python3/dist-packages/lutris/runners/runner.py", line 186, in get_env
    runtime_env = self.get_runtime_env()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 789, in get_runtime_env
    for proton_path in get_proton_paths():
  File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 49, in get_proton_paths
    for path in _iter_proton_locations():
  File "/usr/lib/python3/dist-packages/lutris/util/wine/wine.py", line 38, in _iter_proton_locations
    for path in [os.path.join(p, "common") for p in steam().get_steamapps_dirs()]:
  File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 243, in get_steamapps_dirs
    library_config = self.get_library_config()
  File "/usr/lib/python3/dist-packages/lutris/runners/steam.py", line 149, in get_library_config
    return read_library_folders(self.steam_data_dir)
  File "/usr/lib/python3/dist-packages/lutris/util/steam/config.py", line 161, in read_library_folders
    library["libraryfolders"].pop("contentstatsid")
KeyError: 'contentstatsid'
```

**Comment by danieljohnson2** [comment]
That bug was fixed back in February. You need to update to a later Lutris, 0.5.9.1 is getting rather ripe.

The latest is 0.5.12, and you can get [the deb here](https://github.com/lutris/lutris/releases). They are working on getting [the PPA](https://launchpad.net/~lutris-team/+archive/ubuntu/lutris)  back too; you can try that if you like

**Comment by geajack** [comment]
I know, I was just about to post a reply.

So here's the thing. I am *positive* that I installed Lutris using the 0.5.12 deb from this Github repo. I still have the .deb here in my Downloads folder. However, my Lutris now displays 0.5.9 in the "About" dialog, and when I open the .deb in the Ubuntu software installer program, it also shows version 0.5.9. I have no idea what's going on.

Is there a way to cleanly update Lutris without losing all my configurations?

**Comment by danieljohnson2** [comment]
Installing the deb should not damage your configurations.

I would guess your problem is that you have Lutris installed more than once; run "which lutris" in the terminal to find out where that 0.5.9.1 is hiding. Maybe in ~/.local/bin, and the .deb installs in /usr/games...

You might try removing every copy of Lutris you can find until they are all gone and Lutris won't run- and then install 0.5.12. Your game configurations should be fine.

**Comment by geajack** [comment]
Well, `which lutris` gives me `/usr/games/lutris` (in the same terminal that produced that debug log).

Okay, I've now uninstalled and reinstalled Lutris several times, and the fault here seems to be with Ubuntu's GUI software installer tool. If I right click the Lutris .deb and choose to "open with" Software Installer, it shows me a Lutris install page with a big Install button, but if you scroll down and check the version it gives you 0.5.9, not 0.5.12 (I'm guessing it's just giving you the one from the PPA). If you hit "Install", you're installing 0.5.9. However, if I install the same .deb in a terminal with apt, I get 0.5.12.

And obviously, after updating to 0.5.12, I can't reproduce the original bug for this ticket anymore.

**Comment by danieljohnson2** [comment]
Yeah, I've seen Ubuntu do that too. You can get a separate program for this like Eddy or Gdebi or something.
