### ISSUE TITLE
Lutris fails to open while attempting to check for runtime updates

### ISSUE THREAD

**Issue by aaaaaa123456789** [lutris/lutris#4820]
### Bug description

When opening Lutris, it pops up the "Checking for runtime updates..." message box, which never goes away. Further inspection of the output of `lutris -d` shows that it's failing to download the easyanticheat update due to a URL parsing error, but the uncaught exception causes the runtime update process to never end.

### How to Reproduce

None: just open the program.

### Expected behavior

Program opens.

### Log output

```shell
(lutris:77246): Gtk-WARNING **: 09:52:03.257: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client
INFO     2023-04-21 09:52:03,259 [startup.init_lutris:173]:Starting Lutris 0.5.12
DEBUG    2023-04-21 09:52:03,283 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
INFO     2023-04-21 09:52:03,326 [startup.check_driver:65]:Running Intel Mesa driver 22.2.5 on Mesa Intel(R) UHD Graphics 620 (KBL GT2) (0x5917)
INFO     2023-04-21 09:52:03,327 [startup.check_driver:77]:GPU: 8086:5917 17AA:3973 (i915 drivers)
Fontconfig warning: ignoring en_neutral.UTF-8: not a valid region tag
DEBUG    2023-04-21 09:52:03,642 [lutriswindow.update_store:448]:Showing 2 games
DEBUG    2023-04-21 09:52:03,651 [http._request:88]:GET https://lutris.net/api/runtimes?enabled=1
DEBUG    2023-04-21 09:52:04,341 [http._request:88]:GET https://lutris.net/api/runtimes/icons
DEBUG    2023-04-21 09:52:05,097 [runtime.should_update:57]:Runtime eac_runtime locally updated on Sat 16 Apr 2022 23:11:17 GMT, remote created on Wed 04 Jan 2023 00:18:46 )
DEBUG    2023-04-21 09:52:05,098 [downloader.start:65]:⬇ https://github.com/lutris/buildbot/releases/download/2022.06.23/eac_runtime.tar.xz
ERROR    2023-04-21 09:52:05,103 [jobs.target:36]:Error while completing task <bound method Downloader.async_download of <lutris.util.downloader.Downloader object at 0x7f4a54966bc0>>: <class 'requests.exceptions.InvalidURL'> Failed to parse: https://github.com/lutris/buildbot/releases/download/2022.06.23/eac_runtime.tar.xz
  File "/usr/lib/python3/dist-packages/lutris/util/jobs.py", line 34, in target
    result = self.function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lutris/util/downloader.py", line 143, in async_download
    response = requests.get(self.url, headers=headers, stream=True, timeout=30)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 384, in prepare_url
    raise InvalidURL(*e.args)
ERROR    2023-04-21 09:52:05,106 [downloader.download_cb:114]:Download failed: Failed to parse: https://github.com/lutris/buildbot/releases/download/2022.06.23/eac_runtime.tar.xz
DEBUG    2023-04-21 09:52:05,201 [runtime.check_download_progress:141]:Runtime update interrupted
```

### System Information

```shell
N/A - can't open Lutris (if you want me to run any alternative commands, let me know)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by danieljohnson2** [comment]
That seems strange. What's not to like about 'https://github.com/lutris/buildbot/releases/download/2022.06.23/eac_runtime.tar.xz'?

Could you please put that URL in your browser and see if you can download that file?

Also, if this is still happening, try just hitting the escape key when it's stalled at the runtime update window. Does that get you into Lutris?

**Comment by aaaaaa123456789** [comment]
The file downloads just fine from a browser and contains what you expect. Hitting Esc opens without issues; here's the missing system information while we're at it:

```
[System]
OS:              Linux Mint 21.1 Vera
Arch:            x86_64
Kernel:          5.19.0-40-generic
Desktop:         X-Cinnamon
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
Physical cores:  4
Logical cores:   8

[Memory]
RAM:             18.7 GB
Swap:            0.0 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 22.2.5
OpenGL Core:     4.6 (Core Profile) Mesa 22.2.5
OpenGL ES:       OpenGL ES 3.2 Mesa 22.2.5
Vulkan:          Supported
```

**Comment by danieljohnson2** [comment]
OK, so there are some bugs here- it should not make you hit ESC, and there are issues with the error reporting here. I've committed some fixes, so the next release should do better on runtime update failure.

*But*, when I do it, it downloads the EAC thing without difficulty. I don't know why you are having trouble.

The best thing I can suggest is that you should try the latest master branch. Download Lutris [from GitHub](https://github.com/lutris/lutris) - do not install it. Just run the bin/lutris script inside.

Does this manage to update the runtime and get EAC installed?

If so, that EAC should work in Lutris 0.5.12 just fine. Should tide you over. But if not, I am at a loss to understand what it does not like about the URL.

**Comment by aaaaaa123456789** [comment]
This one opens just fine, but the download still fails. I wonder if the version in the Mint package manager is different somehow?

```
[18:29:04] ax6@n3 ~/Desktop/temp $ gh repo clone lutris/lutris
Cloning into 'lutris'...
remote: Enumerating objects: 51757, done.
remote: Counting objects: 100% (1119/1119), done.
remote: Compressing objects: 100% (452/452), done.
remote: Total 51757 (delta 835), reused 790 (delta 665), pack-reused 50638
Receiving objects: 100% (51757/51757), 17.91 MiB | 8.87 MiB/s, done.
Resolving deltas: 100% (39449/39449), done.
[18:29:30] ax6@n3 ~/Desktop/temp $ cd lutris
[18:29:32] ax6@n3 ~/Desktop/temp/lutris $ bin/lutris

(lutris:91048): Gtk-WARNING **: 18:29:37.621: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client
2023-04-21 18:29:37,624: Starting Lutris 0.5.13
2023-04-21 18:29:37,626: Running Intel Mesa driver 22.2.5 on Mesa Intel(R) UHD Graphics 620 (KBL GT2) (0x5917)
2023-04-21 18:29:37,626: GPU: 8086:5917 17AA:3973 (i915 drivers)
Fontconfig warning: ignoring en_neutral.UTF-8: not a valid region tag
2023-04-21 18:29:39,400: Download failed: Failed to parse: https://github.com/lutris/buildbot/releases/download/2022.06.23/eac_runtime.tar.xz
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 382, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 394, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: https://github.com/lutris/buildbot/releases/download/2022.06.23/eac_runtime.tar.xz

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ax6/Desktop/temp/lutris/lutris/util/downloader.py", line 141, in async_download
    response = requests.get(self.url, headers=headers, stream=True, timeout=30, cookies=self.cookies)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 384, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: https://github.com/lutris/buildbot/releases/download/2022.06.23/eac_runtime.tar.xz
2023-04-21 18:29:39,497: Runtime update completed.
2023-04-21 18:29:40,386: Downloading DXVK v2.1...
2023-04-21 18:29:40,393: Downloading https://github.com/lutris/dxvk/releases/download/v2.1/dxvk-2.1.tar.xz to /home/ax6/.local/share/lutris/runtime/dxvk/dxvk-2.1.tar.xz
2023-04-21 18:29:42,375: Extracting /home/ax6/.local/share/lutris/runtime/dxvk/dxvk-2.1.tar.xz to /home/ax6/.local/share/lutris/runtime/dxvk/v2.1
2023-04-21 18:29:43,922: Downloading DXVK-NVAPI v0.6.2...
2023-04-21 18:29:43,926: Downloading https://github.com/lutris/dxvk-nvapi/releases/download/v0.6.2/dxvk-nvapi-v0.6.2.tar.xz to /home/ax6/.local/share/lutris/runtime/dxvk-nvapi/dxvk-nvapi-v0.6.2.tar.xz
2023-04-21 18:29:45,482: Extracting /home/ax6/.local/share/lutris/runtime/dxvk-nvapi/dxvk-nvapi-v0.6.2.tar.xz to /home/ax6/.local/share/lutris/runtime/dxvk-nvapi/v0.6.2
2023-04-21 18:29:45,924: Downloading VKD3D v2.8...
2023-04-21 18:29:45,927: Downloading https://github.com/lutris/vkd3d/releases/download/v2.8/vkd3d-v2.8.tar.xz to /home/ax6/.local/share/lutris/runtime/vkd3d/vkd3d-v2.8.tar.xz
2023-04-21 18:29:47,063: Extracting /home/ax6/.local/share/lutris/runtime/vkd3d/vkd3d-v2.8.tar.xz to /home/ax6/.local/share/lutris/runtime/vkd3d/v2.8
2023-04-21 18:29:48,003: Downloading dgvoodoo2 v2.8...
2023-04-21 18:29:48,005: Downloading https://github.com/lutris/dgvoodoo2/releases/download/v2.8/dgvoodoo2-v2.8.tar.xz to /home/ax6/.local/share/lutris/runtime/dgvoodoo2/dgvoodoo2-v2.8.tar.xz
2023-04-21 18:29:49,066: Extracting /home/ax6/.local/share/lutris/runtime/dgvoodoo2/dgvoodoo2-v2.8.tar.xz to /home/ax6/.local/share/lutris/runtime/dgvoodoo2/v2.8
2023-04-21 18:29:49,162: Startup complete
2023-04-21 18:29:52,176: Shutting down Lutris```

**Comment by danieljohnson2** [comment]
Mysterious. You managed to download a bunch of other components. They look very similar; why did the EAC one fail?

I suspect perhaps you have a older version of Python than I do, and maybe there's an issue with that version of urllib3 somehow. But it is very obscure.

**Comment by aaaaaa123456789** [comment]
You tell me: ```
[18:29:52] ax6@n3 ~/Desktop/temp/lutris $ python3 --version
Python 3.10.6
[18:58:07] ax6@n3 ~/Desktop/temp/lutris $ pip show urllib3
Name: urllib3
Version: 1.26.5
Summary: HTTP library with thread-safe connection pooling, file post, and more.
Home-page: https://urllib3.readthedocs.io/
Author: Andrey Petrov
Author-email: andrey.petrov@shazow.net
License: MIT
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by: ```

**Comment by danieljohnson2** [comment]
That is exactly what I have. So much for that theory.

**Comment by tridoxx** [comment]
how you install lutris?, from the website?, using the software store deb or snap?

**Comment by aaaaaa123456789** [comment]
From your apt repository.

**Comment by strycore** [comment]
If you read the error message, you notice it doesn't fail to download the file, it fails to parse the URL which is even weirder because it's a perfectly valid URL and no one else has issues with it.

The error is not in Lutris so the origin of Lutris is not important here.

Might be worth inspecting in the requests package what is going on in the models module.

**Comment by strycore** [comment]
Other problems I see in the log: 

`(lutris:91048): Gtk-WARNING **: 18:29:37.621: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client`


`Fontconfig warning: ignoring en_neutral.UTF-8: not a valid region tag`

**Comment by aaaaaa123456789** [comment]
The second one is because I have a custom locale configured, which _everything_ seems to hate (basically everything that uses the locale _name_ instead of the locale data, for some odd reason)

**Comment by strycore** [comment]
Found the related issue: https://github.com/psf/requests/issues/5476

Apparently the workaround is to update six ( `pip3 install six==1.15.0` )

I'm going to blame Linux Mint because it's always the correct thing to do.
