### ISSUE TITLE
Incompatible Wine version detected

### ISSUE THREAD

**Issue by Smoukus** [lutris/lutris#4904]
### Bug description

As of latest commits, I can't run any games with Fsync or Esync toggles in Lutris enabled.

I use [TKG's](https://github.com/Frogging-Family/wine-tkg-git) self compiled Wine, and as of today's commits, I can't run any game if I have Fsync or Esync toggles enabled.
I get the following error:
![image](https://github.com/lutris/lutris/assets/48409293/f91f74ea-1ad9-4b26-bb64-3b4bd8fb93f5)

I am pretty sure that this commit has introduced this error:
https://github.com/lutris/lutris/commit/6821aafa2be40aa93ad3dba9cf923cb6fe56a161

Here's the Wine that I use in Lutris:
![image](https://github.com/lutris/lutris/assets/48409293/168a26da-76f6-4ac7-b748-a0db09bbd0a7)

On my Wine version, both Fsync and Esync work properly.

### How to Reproduce

Get Wine TKG Wine
Make sure that Esync/Fsync toggles are enabled
Start any game

### Expected behavior

Games should run normally because my Wine supports Fsync/Esync

### Log output

```shell
INFO     2023-06-14 21:31:15,381 [startup.init_lutris:203]:Starting Lutris 0.5.13
INFO     2023-06-14 21:31:15,382 [startup.check_driver:73]:Running AMD Mesa driver 23.2.0 on AMD Radeon RX 6800 XT (navi21, LLVM 15.0.7, DRM 3.52, 6.3.7-273-tkg-cfs) (0x73bf)
INFO     2023-06-14 21:31:15,382 [startup.check_driver:85]:GPU: 1002:73BF 1EAE:6701 (amdgpu drivers)
DEBUG    2023-06-14 21:31:15,452 [xrandr._get_vidmodes:16]:Retrieving video modes from XrandR
DEBUG    2023-06-14 21:31:15,493 [lutris.get_missing_game_ids:191]:Checking for missing games
DEBUG    2023-06-14 21:31:16,614 [grid.on_item_activated:100]:Item activated: 3
INFO     2023-06-14 21:31:16,672 [runner.use_runtime:391]:Runtime disabled by system configuration
ERROR    2023-06-14 21:31:17,540 [exceptions.wrapper:95]:Battle Net (wine) has encountered an error: Unhandled error: NON_FSYNC_WINE_VERSION
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lutris/exceptions.py", line 89, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 603, in configure_game
    gameplay_info = self.get_gameplay_info(launch_ui_delegate)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lutris/game.py", line 583, in get_gameplay_info
    raise self.get_config_error(gameplay_info)
lutris.exceptions.GameConfigError: Unhandled error: NON_FSYNC_WINE_VERSION
DEBUG    2023-06-14 21:31:17,541 [application.on_game_stop:679]:Removing 3 from running IDs
INFO     2023-06-14 21:31:20,142 [application.do_shutdown:960]:Shutting down Lutris
```
```


### System Information

```shell
[System]
OS:              EndeavourOS rolling rolling
Arch:            x86_64
Kernel:          6.3.7-273-tkg-cfs
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 5900X 12-Core Processor
Physical cores:  12
Logical cores:   24

[Memory]
RAM:             31.3 GB
Swap:            0.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6800 XT (navi21, LLVM 15.0.7, DRM 3.52, 6.3.7-273-tkg-cfs)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.2.0-devel (git-b79f6ec397)
OpenGL Core:     4.6 (Core Profile) Mesa 23.2.0-devel (git-b79f6ec397)
OpenGL ES:       OpenGL ES 3.2 Mesa 23.2.0-devel (git-b79f6ec397)
Vulkan Version:  1.3.253
Vulkan Drivers:  AMD Radeon RX 6800 XT (RADV NAVI21) (1.3.251)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
Fixed by b368f82e26d47e6a5536435a4f73f34c7ecc3c04

**Comment by Smoukus** [comment]
> Fixed by [b368f82](https://github.com/lutris/lutris/commit/b368f82e26d47e6a5536435a4f73f34c7ecc3c04)

Nope, it still happens.

Also, when I have only Esync toggle enabled, I get this message:
![image](https://github.com/lutris/lutris/assets/48409293/a63ea980-fdbc-4800-b44c-601d4e41972b)

**Comment by strycore** [comment]
92fe3935be1019444d1facfb79053010d4aa0cf6 should fix it

**Comment by Smoukus** [comment]
> [92fe393](https://github.com/lutris/lutris/commit/92fe3935be1019444d1facfb79053010d4aa0cf6) should fix it

That fixes it, yep. Thanks!
