### ISSUE TITLE
EA App's offerIds parameter to launch games have changed from Origin

### ISSUE THREAD

**Issue by italoghost** [lutris/lutris#4996]
### Bug description

If I understand the "ea_app.py" file correctly, you are using the game's ID on the platform as the `offerIds`. However, for the EA App, you need to use the parameters between the `<contentID>` in the "installerdata.xml" files within the games' installation folders.

This [Playnite issue has more information](https://github.com/JosefNemec/PlayniteExtensions/issues/13).

I have been configuring manually my EA App games since Origin was discontinued and it has been working flawlessly. For example, Dead Space is launched with the following commands:

`origin2://game/launch/?offerIds=1002975,1003943,1009227,1009228,deadspace_na,deadspace_eu1,deadspace_eu2,deadspace_eu3`

And Battlefield 4 is launched with these:

`origin2://game/launch/?offerIds=1007968,1011575,1011576,1011577,1010268,1010269,1010270,1010271,1010958,1010959,1010960,1010961,1007077,1016751,1016757,1016754,1015365,1015364,1015363,1015362`

### How to Reproduce

1. Try to launch a game from the new "EA App" implementation.
2. It won't launch the game, only the EA App.

### Expected behavior

Launch the game properly.

### Log output

```shell
No logs.
```

### System Information

```shell
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.4.11-zen2-1-zen
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 2700 Eight-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             15.5 GB
Swap:            4.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 570 Series (polaris10, LLVM 15.0.7, DRM 3.52, 6.4.11-zen2-1-zen)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.6
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.6
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.6
Vulkan Version:  1.3.255
Vulkan Drivers:  AMD Radeon RX 570 Series (RADV POLARIS10) (1.3.246)
```

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by strycore** [comment]
I don't trust the OfferId system. I don't trust the games will launch properly or that we'll easily manage to find the correct launch parameters.
Finding the installed games via EA App's files is almost impossible and involves cracking and reverse engineering an encrypted file in the user's documents. (See: https://github.com/erri120/erri120.github.io/issues/45#issuecomment-1595915665 )

What I want to rely instead is launch EA App by itself and then launch the game executable, which is something that has reliably worked in the past.
Finding installed games will be as easy as listing the contents of `Program Files/EA Games/` and maintaining a mapping of directory name to executable.

**Comment by strycore** [comment]
So your solution is going to be a lot easier to implement. I've tried launching games with the OfferIds arguments and so far it works but I'm getting a password prompt every time I launch a game.

**Comment by italoghost** [comment]
Does this happen with every game? Because both Battlefield 4 and Dead Space launch just fine to me, not needing to put my password. 

With some Ubisoft games (such Far Cry 3 and some Assassin's Creed games), I had to put my password every time I tried to play.

**Comment by strycore** [comment]
I've had this happen with Battlefield Hardline and Need For Speed

**Comment by italoghost** [comment]
Did you add all the parameters?

**Comment by strycore** [comment]
I don't get long list of content IDs in my case. I only get a single ID. Which gets the game to run.

I've committed the change to use the contentIDs, this can be tested now.

**Comment by italoghost** [comment]
I think it is still not working as expected. I am on the latest commit (`lutris-git 0.5.13.r228.g63faa216-1`) and tried to install Plants vs Zombies through the EA App service. It launched the EA App but it didn't do anything. Then I manually forced the installation of the game and quit.

Trying to launch the game through the game card didn't work, as the launch argument does not contain the parameter of the `contentId`:

`origin2://game/launch?offerIds=OFB-EAST:48217&autoDownload=1`

The content of the "installerdata.xml":

`<contentID>71592</contentID>`

**Comment by italoghost** [comment]
I think that there is a missing "s" on the `offerIds` of the "ea_app.py":

`def get_launch_arguments(content_id, action="launch"):

if action == "launch":

return "origin2://game/launch?offerIds=%s&autoDownload=1" % content_id

if action == "download":

return "origin2://game/download?offerId=%s" % content_id`

**Comment by strycore** [comment]
I tried with offerIds but it didn't trigger an install. Instead, I'm using launch all the time now and the EA App will show a "Get the game" dialog when an install is needed.

I seem to remember reading somewhere that "origin2://game/download" wasn't implemented in EA App.

> origin2://game/launch?offerIds=OFB-EAST:48217&autoDownload=1

You shouldn't get that, you should get the Content ID, make sure to refresh your game list for EA App.

**Comment by strycore** [comment]
On my gaming machine, I don't have the sign in issues. The EA App runs quite nicely.

**Comment by italoghost** [comment]
I will try tomorrow and give you a feedback!

**Comment by italoghost** [comment]
It is now launching and installing correctly. But I found that it does not catch all the `contentIds`, just the first one. For example, I clicked to "install" Battlefield 4 (which was already installed) and this was the output:

`origin2://game/launch?offerIds=1011577&autoDownload=1`

Although it worked, I don't know if by catching only one `contentId` can create problems in the future.

**Comment by strycore** [comment]
I've never seen a XML file that had multiple IDs in it. And if the game wasn't installed beforehand then the content ID comes from EA's API, not the XML file (which doesn't exist). EA's API offers one ContentID field in the JSON response and that's it. 

I suspect that the other IDs are related to DLC so that would be safe to ignore.

**Comment by strycore** [comment]
I've encountered no issue with the EA App integration. Shortcuts are working well.

**Comment by KurashiAOI** [comment]
> I've encountered no issue with the EA App integration. Shortcuts are working well.

hi, how did you manage to integrate EA App? Does EA Play games also works? Thanks

**Comment by strycore** [comment]
The EA App integration is complete already
