### ISSUE TITLE
Games can no longer be launched from steam deck gaming mode

### ISSUE THREAD

**Issue by Nevon** [lutris/lutris#5509]
### Bug description

When launching a game from the steam deck gaming mode, installed using the flatpak version of Lutris 0.5.17, it immediately crashes/fails to launch. Launching the same game from Lutris in desktop mode, the game runs with no issues.

I saw related issues that seemed to be caused by using a proton runner, or by converting a wine prefix from wine to proton or the other way around, so to verify I created a new prefix using the default wine-ge-8-26-x86_64 runner, and was able to reproduce the same issue. Potentially related issues: #5422 #5436 

This seems to be a regression, as this issue wasn't present before a Lutris version upgrade, after which none of my games would launch in gaming mode anymore. I believe this was introduced in 0.5.17, but I will try to downgrade to verify. It could also be an update to Steam or the OS that happened at the same time, but I can't verify that.

### How to Reproduce

1. Install any (I can't be sure of this, but so far it seems like any) game using the default wine runner in the flatpak version of Lutris 0.5.17. 
2. Launch the game from desktop mode and see that it runs.
3. Create a steam shortcut by right clicking on the game in Lutris and clicking the relevant menu item
4. Go back to gaming mode and launch the game, and see that it fails to start.

### Expected behavior

I expected it to run the games same as it used to.

### Log output

```shell
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Started initial process 75 from gamemoderun /home/deck/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine /run/media/deck/SD1/Games/eiyuden-chronicles-hundred-heroes-fixed/drive_c/GOG Games/Eiyuden Chronicle Hundred Heroes/EiyudenChronicle.exe
Start monitoring process.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
gamemodeauto: 
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
gamemodeauto: 
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
[UnityMemory] Configuration Parameters - Can be set up in boot.config
    "memorysetup-bucket-allocator-granularity=16"
    "memorysetup-bucket-allocator-bucket-count=8"
    "memorysetup-bucket-allocator-block-size=4194304"
    "memorysetup-bucket-allocator-block-count=1"
    "memorysetup-main-allocator-block-size=16777216"
    "memorysetup-thread-allocator-block-size=16777216"
    "memorysetup-gfx-main-allocator-block-size=16777216"
    "memorysetup-gfx-thread-allocator-block-size=16777216"
    "memorysetup-cache-allocator-block-size=4194304"
    "memorysetup-typetree-allocator-block-size=2097152"
    "memorysetup-profiler-bucket-allocator-granularity=16"
    "memorysetup-profiler-bucket-allocator-bucket-count=8"
    "memorysetup-profiler-bucket-allocator-block-size=4194304"
    "memorysetup-profiler-bucket-allocator-block-count=1"
    "memorysetup-profiler-allocator-block-size=16777216"
    "memorysetup-profiler-editor-allocator-block-size=1048576"
    "memorysetup-temp-allocator-size-main=4194304"
    "memorysetup-job-temp-allocator-block-size=2097152"
    "memorysetup-job-temp-allocator-block-size-background=1048576"
    "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
    "memorysetup-temp-allocator-size-background-worker=32768"
    "memorysetup-temp-allocator-size-job-worker=262144"
    "memorysetup-temp-allocator-size-preload-manager=262144"
    "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
    "memorysetup-temp-allocator-size-audio-worker=65536"
    "memorysetup-temp-allocator-size-cloud-worker=32768"
    "memorysetup-temp-allocator-size-gfx=262144"
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
[Gamescope WSI] Forcing on VK_EXT_swapchain_maintenance1.
radv: Can't open file: '/tmp/radv_vrs.jU60M8qm'.
radv: Failed to initialize the notifier for RADV_FORCE_VRS_CONFIG_FILE!
[Gamescope WSI] Forcing on VK_EXT_swapchain_maintenance1.
radv: Can't open file: '/tmp/radv_vrs.jU60M8qm'.
radv: Failed to initialize the notifier for RADV_FORCE_VRS_CONFIG_FILE!
[Gamescope WSI] Creating Gamescope surface: xid: 0xe00034
[Gamescope WSI] Atom of T was wrong type. Expected XCB_ATOM_CARDINAL.
[Gamescope WSI] Made gamescope surface for xid: 0xe00034
[Gamescope WSI] Surface state:
  steam app id:                  0
  window xid:                    0xe00034
  wayland surface res id:        4
  layer client flags:            0x4
  server hdr output enabled:     true
  hdr formats exposed to client: true
[Gamescope WSI] Creating swapchain for xid: 0xe00034 - minImageCount: 4 - format: VK_FORMAT_R8G8B8A8_UNORM - colorspace: VK_COLOR_SPACE_SRGB_NONLINEAR_KHR - flip: true
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Initial process has exited (return code: 768)
Monitored process exited.
Exit with return code 768
```
```


### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: NO
Gamemode: YES
Steam: YES
In Flatpak: YES
[System]
OS: GNOME 45 Flatpak runtime
Arch: x86_64
Kernel: 6.1.52-valve16-1-neptune-61
Desktop: KDE
Display Server: x11
[CPU]
Vendor: AuthenticAMD
Model: AMD Custom APU 0932
Physical cores: 4
Logical cores: 8
[Memory]
RAM: 14.5 GB
Swap: 1.0 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon Graphics (radeonsi, vangogh, LLVM 17.0.6, DRM 3.54, 6.1.52-valve16-1-neptune-61)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.0.7 (git-cc175010c5)
OpenGL Core: 4.6 (Core Profile) Mesa 24.0.7 (git-cc175010c5)
OpenGL ES: OpenGL ES 3.2 Mesa 24.0.7 (git-cc175010c5)
Vulkan Version: 1.3.261
Vulkan Drivers: AMD Radeon Graphics (RADV VANGOGH) (1.3.274)
```

**Comment by Nevon** [comment]
I think my theory that it's related to the latest Lutris update seems busted. I just tried downgrading to 0.5.16, and had the exact same outcome. I also tested creating a new, clean wine prefix and ran the same executable using that prefix, and it also failed to launch when running from gaming mode. I distinctly remember upgrading Lutris just before this problem started (I just didn't get around to reporting it until now), but my experimentation seems to show that it's not because of this update.

**Comment by R1kaB3rN** [comment]
Thanks for reporting this. The Lutris team and umu maintainers are aware of this, and this bug has [already been reported upstream](https://github.com/ValveSoftware/gamescope/issues/1341).

**Comment by Nevon** [comment]
Thank you very much for linking the upstream issue. Am I correct in understanding that this is an issue with gamescope, rather than anything to do with Lutris?

What confuses me a bit is that the related issues all seem to say that the issue only occurs when using Proton and umu-launcher, and that reverting to using Wine solves the issue, whereas in my case it fails whether I'm using Wine or proton, with a version of Lutris that uses umu or not.

**Comment by R1kaB3rN** [comment]
Internally, Lutris uses umu-launcher as its runtime and if you're using the Lutris Flatpak (0.5.17) and have configured it to use Proton to run games, then this issue is not Lutris'. However, this issue is not exclusively Lutris' but should effect all Flatpak applications that uses its own bundle of the Steam Runtime (umu-launcher) when running games within the SteamOS gamescope session. 

If you're still experiencing this issue with wine-ge though, then keep this issue open.

**Comment by Acor3D** [comment]
Peeking in to report I also experience this issue with all lutris games regardless of runner used, tried some suggestions I saw around to no avail.
Lutris in desktop mode launches games just fine, and shortcuts created through 'right click > create steam shortcut' work within steam in desktop mode, it's only game mode that fails to launch those very same shortcuts.

Suggestions attempted include:
- Creating a desktop shortcut, then adding that shortcut as a non-steam game on steam
- Double checking steam was not overriding wine prefixes/proton versions (it wasn't from what I can tell)
- Running windows games directly under steam as non-steam games without lutris (works for windows games, but not for other runners naturally)

Not very tech savvy, but I will keep experimenting and report back if I find some success

**Comment by R1kaB3rN** [comment]
Putting the reported Wine-GE problem aside, the Steam Deck deck gaming mode problem has already been addressed in the latest main branch of umu-launcher. So, it's up to Lutris push the updates for umu-launcher or make a new point release.

**Comment by NSArtem** [comment]
Any update on the issue? As of now it's still reproducible, just encountered this problem with Proton-GE custom runner in the latest Lutris.

**Comment by mrblack7** [comment]
Having the same issue here at the moment. Adding the shortcut to Steam works fine, and the game works in Desktop mode, but won't launch when in Game mode.

**Comment by getBoolean** [comment]
It works using the lutris version of GE Proton, the exact version I've been using is `lutris-GE-Proton8-26-x86_64`

**Comment by WhiteBahamut** [comment]
Facing the same issue, can't find the github ticket anymore (probably in Proton-GE), that this seems to be an issue since the introduction of umu. Older versions before umu work

**Comment by cubegamerx** [comment]
How do you downgrade lutris? Can someone give me the exact steps?

**Comment by feday2** [comment]
100% working method is to create new prefix.
Dont forget transfer games save and install required libs

**Comment by rmatec** [comment]
Any update/workaround on this? No game is working on my Steam Deck in game mode. I have tried different runtimes and even downgraded Lutris but the issue persists.

**Comment by nullrupo** [comment]
still happens in lutris flatpak 0.5.18, the game runs, audio plays in the background, but doesnt display in gamemode

**Comment by WhiteBahamut** [comment]
Since I updated to 0.5.18 it fails again. Used Warehouse to ho back to prev lutris version (https://ubuntuhandbook.org/index.php/2024/11/downgrade-flatpak-package/amp/).

**Comment by Atoshx** [comment]
currently a fix in 0.5.18 is using the environment variable `PROTON_VERB=waitforexitandrun` until this gets fixed

**Comment by danieljohnson2** [comment]
This has been changed in master already, so it should work in the next release.

**Comment by aph11** [comment]
> currently a fix in 0.5.18 is using the environment variable `PROTON_VERB=waitforexitandrun` until this gets fixed

Where do you put this environment variable ? I tried with flatseal and as a global option in lutris config but it does not work when using Proton 9 or experimental. However with wine-ge-8-26 everything is fine even without the env var.

The game launches I can hear audio but it's displaying the steam loading screen.

**Comment by domb84** [comment]
> currently a fix in 0.5.18 is using the environment variable `PROTON_VERB=waitforexitandrun` until this gets fixed

This works for me, add it under the wine config in lutris.

**Comment by JamesIV4** [comment]
I'm having this issue as well after the lastest Proton update. It broke all Lutris game installs and all Heroic game installs. They all have the infinite spinner Steam logo while the game audio plays in the background, in game mode.

Desktop mode works fine but of course no Steam Input controls that way.

I was able to bypass the issue by using NonSteamLaunchers for Decky. Then games work in game mode.

This still leaves dozens of downloaded and installed (included modded and tricky to run games) broken. Lutris has been the best so far at getting obscure old games to run, so I really don't want to abandon using it.

I've been using "Proton - Experimental" for every game that will support it through Lutris as it gets the best performance. Is that inadvisable?

Attached is a log file running Sims 2 Ultimate Collection through the EA app in game mode.

[sims2.log](https://github.com/user-attachments/files/18761001/sims2.log)

**Comment by JamesIV4** [comment]
I forgot to mention, the issue isn't happening in Wine GE (default) runner, so I'm using that now.

**Comment by ayasme** [comment]
> This has been changed in master already, so it should work in the next release.

Any estimate on when this will make it into the flatpak release?

**Comment by danieljohnson2** [comment]
> > This has been changed in master already, so it should work in the next release.
> 
> Any estimate on when this will make it into the flatpak release?

"Real soon now!"

Sorry, can't be specific. It'll happen when 0.5.19 drops, and that's on the way, but the timing is all up to @strycore.

**Comment by strycore** [comment]
It's not up to me. Everyone is able to help QA the current and say this is ok to ship.
 
I'm not QAing the Lutris client at the moment, and afaik, no one is doing it. So if you guys are waiting for me, you can end up waiting a long time and if no one QAs the client before release then we'll end up pushing another bad release like 0.5.18 was.

**Comment by danieljohnson2** [comment]
Oh, look, there's 0.5.19 now!

The Flatpak always takes a while to drop though, and at this writing the .deb isn't done yet either, so just keep holding your breath people!

Also, @strycore, I'd remind you that we've got a new icon in GIT up for MelonDS, so it'd be nice if you could publish a new icon 'runtime'.

**Comment by rmatec** [comment]
> It's not up to me. Everyone is able to help QA the current and say this is ok to ship.
> 
> I'm not QAing the Lutris client at the moment, and afaik, no one is doing it. So if you guys are waiting for me, you can end up waiting a long time and if no one QAs the client before release then we'll end up pushing another bad release like 0.5.18 was.

That is all right and I agree with your statement. However, the reality is people will stop using Lutris if it simply does not work. I ditched it myself months ago. Still all right if you do not mind that.

**Comment by danieljohnson2** [comment]
We're doing the last minute fixes now, *after* releasing 0.5.19, so I think it might have been a bit premature.

**Comment by domb84** [comment]
This issue has returned for me on the latest steam deck update. Previously setting “waitforexitandrun” would work but no longer

**Comment by Wh1t3Rose** [comment]
Same issue here also on latest Steam Deck Update
