### ISSUE TITLE
[beta 0.5.20] Lutris does not kill all processes when using Gamescope

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris#6280]
### Bug description

When using Gamescope option in Lutris, when you quit a Wine game, some processes are not killed

### How to Reproduce

1) activate Gamescope for a Wine game
2) launch game
3) quit games
4) some processes are not killed when you quit game, even when you click on Lutris "Stop" button
5) when you click on Stop button, it does not kill on the remaining processes and much worse, sometimes it launches new processes...

### Expected behavior

When I quit a game launched with Lutris, Lutris should verify all processes related to this game is close and should kill remaining ones

### Log output

```shell
Remaining processes not killed by Lutris are always the same, some examples:

python3 /usr/share/lutris/bin/lutris-wrapper Age of Wonders 0 0 gamescope -f -- gamemoderun /home/romain/.local/share/lutris/runtime/umu/umu-run /home/romain/Games/gog/age-of-wonders/drive_c/GOG Games/Age of Wonders/AoW.exe

gamescopereaper -- gamemoderun /home/romain/.local/share/lutris/runtime/umu/umu-run /home/romain/Games/gog/age-of-wonders/drive_c/GOG Games/Age of Wonders/AoW.exe

                                                                                                                                            
gamescope-brokey --mangoapp -r 30 -f --mangoapp -- gamemoderun /home/romain/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine /home/romain/Games2/mechwarrior-3/drive_c/MicroProse/MechWarrior3/Mech3fixup.exe

gamescopereaper -- gamemoderun /home/romain/.var/app/net.lutris.Lutris/data/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine /home/romain/Games2/mechwarrior-3/drive_c/MicroProse/MechWarrior3/Mech3fixup.exe

C:\windows\system32\winedevice.exe
```

### System Information

```shell
Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: YES
[System]
OS: GNOME 46 Flatpak runtime
Arch: x86_64
Kernel: 6.16.8-1-MANJARO
Lutris Version: 0.5.19
Desktop: XFCE
Display Server: x11
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 9 5900HX with Radeon Graphics
Physical cores: 8
Logical cores: 16
[Memory]
RAM: 30.8 GB
Swap: 16.2 GB
[Graphics]
Vendor: AMD
OpenGL Renderer: AMD Radeon RX 6600M (radeonsi, navi23, LLVM 17.0.6, DRM 3.64, 6.16.8-1-MANJARO)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 25.0.7 (git-742a20f48c)
OpenGL Core: 4.6 (Core Profile) Mesa 25.0.7 (git-742a20f48c)
OpenGL ES: OpenGL ES 3.2 Mesa 25.0.7 (git-742a20f48c)
Vulkan Version: 1.3.261
Vulkan Drivers: AMD Radeon RX 6600M (RADV NAVI23) (1.4.305), AMD Radeon Graphics (RADV RENOIR) (1.4.305)
```

### Media (optional)

<img width="698" height="604" alt="Image" src="https://github.com/user-attachments/assets/f7281147-33ed-4a8e-80b3-884713094615" />

**Comment by MichelN86** [comment]
This is a bug with gamescope, Heroic Game Launcher has the same issue. When you alt + f4 out of game, when you close the game the normal way this does not happen btw.

**Comment by legluondunet** [comment]
@MichelN86 In any case, Lutris should check that all processes related to a game it has launched are closed and, if not, kill them, including GameScope processes.

> This is a bug with gamescope, Heroic Game Launcher has the same issue. When you alt + f4 out of game, when you close the game the normal way this does not happen btw.

No, that could even happened the normal way.

**Comment by Anagastes** [comment]
I can confirm the problem, but with Lutris 0.5.19...

<img width="1616" height="454" alt="Image" src="https://github.com/user-attachments/assets/4499c3fd-44bb-435d-8098-4dd1900ece13" />

I think it's more of a bug in Gamescope. It also occurs when starting the game manually directly with Gamescope (without Lutris).

Here my start cmd for it.

<img width="1070" height="273" alt="Image" src="https://github.com/user-attachments/assets/d79a16ff-a396-452f-97e0-a770fb765128" />

And yes, i switch between the game and desktop with alt+tab etc. :)

**Comment by strycore** [comment]
try with the fix I've commited

**Comment by Anagastes** [comment]
> try with the fix I've commited

Thank you for your prompt reply and your work. Now the “force quit” function works in the Lutris user interface. However, it does not work automatically when the game is closed... 🙈 I'm sorry...

**Comment by legluondunet** [comment]
This commit does not seem to resolve this issue:
I launched a game with Gamescope activated, latest Lutris dev code 18 january 2026.
After game closed, this processes still alived:

`gamescope --mangoapp -f --force-grab-cursor -- gamemoderun taskset -c 0-0 /home/romain/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine /home/romain/Games/spider-man-2001/drive_c/Program Files (x86)/Activision/Spider-Man/SpideyPC.exe`

`gamescopereaper -- gamemoderun taskset -c 0-0 /home/romain/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine /home/romain/Games/spider-man-2001/drive_c/Program Files (x86)/Activision/Spider-Man/SpideyPC.exe`

Press Lutris Stop button does not close this processes.

**Comment by legluondunet** [comment]
more details: I can no more reproduce this issue with Proton-GE latest or GE-Proton latest or Valve Proton-Experimental.
But issue is still present with non Proton Wine version like Wine-Staging.

**Comment by Zebra2711** [comment]
> more details: I can no more reproduce this issue with Proton-GE latest or GE-Proton latest or Valve Proton-Experimental. But issue is still present with non Proton Wine version like Wine-Staging.

Maybe because this wine bug is fixed upstream, but wine-staging 11 does not include this MR yet
https://gitlab.winehq.org/wine/wine/-/merge_requests/9890

**Comment by legluondunet** [comment]
If I force a game close wit halt+F4, some Gamescope processes still persist...Could Lutris be more efficient on this? Could it manage Wine non Proton version too?
